EXPECTED = {'E2AP-Constants': {'extensibility-implied': False,
                    'imports': {'E2AP-CommonDataTypes': ['ProcedureCode',
                                                         'ProtocolIE-ID']},
                    'object-classes': {},
                    'object-sets': {},
                    'tags': 'AUTOMATIC',
                    'types': {},
                    'values': {'id-Cause': {'type': 'ProtocolIE-ID',
                                            'value': 1},
                               'id-CriticalityDiagnostics': {'type': 'ProtocolIE-ID',
                                                             'value': 2},
                               'id-E2connectionFailed-Item': {'type': 'ProtocolIE-ID',
                                                              'value': 42},
                               'id-E2connectionSetup': {'type': 'ProtocolIE-ID',
                                                        'value': 39},
                               'id-E2connectionSetupFailed': {'type': 'ProtocolIE-ID',
                                                              'value': 40},
                               'id-E2connectionSetupFailed-Item': {'type': 'ProtocolIE-ID',
                                                                   'value': 41},
                               'id-E2connectionUpdate': {'type': 'ProcedureCode',
                                                         'value': 11},
                               'id-E2connectionUpdate-Item': {'type': 'ProtocolIE-ID',
                                                              'value': 43},
                               'id-E2connectionUpdateAdd': {'type': 'ProtocolIE-ID',
                                                            'value': 44},
                               'id-E2connectionUpdateModify': {'type': 'ProtocolIE-ID',
                                                               'value': 45},
                               'id-E2connectionUpdateRemove': {'type': 'ProtocolIE-ID',
                                                               'value': 46},
                               'id-E2connectionUpdateRemove-Item': {'type': 'ProtocolIE-ID',
                                                                    'value': 47},
                               'id-E2nodeComponentConfigAddition': {'type': 'ProtocolIE-ID',
                                                                    'value': 50},
                               'id-E2nodeComponentConfigAddition-Item': {'type': 'ProtocolIE-ID',
                                                                         'value': 51},
                               'id-E2nodeComponentConfigAdditionAck': {'type': 'ProtocolIE-ID',
                                                                       'value': 52},
                               'id-E2nodeComponentConfigAdditionAck-Item': {'type': 'ProtocolIE-ID',
                                                                            'value': 53},
                               'id-E2nodeComponentConfigRemoval': {'type': 'ProtocolIE-ID',
                                                                   'value': 54},
                               'id-E2nodeComponentConfigRemoval-Item': {'type': 'ProtocolIE-ID',
                                                                        'value': 55},
                               'id-E2nodeComponentConfigRemovalAck': {'type': 'ProtocolIE-ID',
                                                                      'value': 56},
                               'id-E2nodeComponentConfigRemovalAck-Item': {'type': 'ProtocolIE-ID',
                                                                           'value': 57},
                               'id-E2nodeComponentConfigUpdate': {'type': 'ProtocolIE-ID',
                                                                  'value': 33},
                               'id-E2nodeComponentConfigUpdate-Item': {'type': 'ProtocolIE-ID',
                                                                       'value': 34},
                               'id-E2nodeComponentConfigUpdateAck': {'type': 'ProtocolIE-ID',
                                                                     'value': 35},
                               'id-E2nodeComponentConfigUpdateAck-Item': {'type': 'ProtocolIE-ID',
                                                                          'value': 36},
                               'id-E2nodeConfigurationUpdate': {'type': 'ProcedureCode',
                                                                'value': 10},
                               'id-E2nodeTNLassociationRemoval': {'type': 'ProtocolIE-ID',
                                                                  'value': 58},
                               'id-E2nodeTNLassociationRemoval-Item': {'type': 'ProtocolIE-ID',
                                                                       'value': 59},
                               'id-E2removal': {'type': 'ProcedureCode',
                                                'value': 13},
                               'id-E2setup': {'type': 'ProcedureCode',
                                              'value': 1},
                               'id-ErrorIndication': {'type': 'ProcedureCode',
                                                      'value': 2},
                               'id-GlobalE2node-ID': {'type': 'ProtocolIE-ID',
                                                      'value': 3},
                               'id-GlobalRIC-ID': {'type': 'ProtocolIE-ID',
                                                   'value': 4},
                               'id-RANfunction-Item': {'type': 'ProtocolIE-ID',
                                                       'value': 8},
                               'id-RANfunctionID': {'type': 'ProtocolIE-ID',
                                                    'value': 5},
                               'id-RANfunctionID-Item': {'type': 'ProtocolIE-ID',
                                                         'value': 6},
                               'id-RANfunctionIEcause-Item': {'type': 'ProtocolIE-ID',
                                                              'value': 7},
                               'id-RANfunctionsAccepted': {'type': 'ProtocolIE-ID',
                                                           'value': 9},
                               'id-RANfunctionsAdded': {'type': 'ProtocolIE-ID',
                                                        'value': 10},
                               'id-RANfunctionsDeleted': {'type': 'ProtocolIE-ID',
                                                          'value': 11},
                               'id-RANfunctionsModified': {'type': 'ProtocolIE-ID',
                                                           'value': 12},
                               'id-RANfunctionsRejected': {'type': 'ProtocolIE-ID',
                                                           'value': 13},
                               'id-RICaction-Admitted-Item': {'type': 'ProtocolIE-ID',
                                                              'value': 14},
                               'id-RICaction-NotAdmitted-Item': {'type': 'ProtocolIE-ID',
                                                                 'value': 16},
                               'id-RICaction-ToBeSetup-Item': {'type': 'ProtocolIE-ID',
                                                               'value': 19},
                               'id-RICactionID': {'type': 'ProtocolIE-ID',
                                                  'value': 15},
                               'id-RICactions-Admitted': {'type': 'ProtocolIE-ID',
                                                          'value': 17},
                               'id-RICactions-NotAdmitted': {'type': 'ProtocolIE-ID',
                                                             'value': 18},
                               'id-RICcallProcessID': {'type': 'ProtocolIE-ID',
                                                       'value': 20},
                               'id-RICcontrol': {'type': 'ProcedureCode',
                                                 'value': 4},
                               'id-RICcontrolAckRequest': {'type': 'ProtocolIE-ID',
                                                           'value': 21},
                               'id-RICcontrolHeader': {'type': 'ProtocolIE-ID',
                                                       'value': 22},
                               'id-RICcontrolMessage': {'type': 'ProtocolIE-ID',
                                                        'value': 23},
                               'id-RICcontrolOutcome': {'type': 'ProtocolIE-ID',
                                                        'value': 32},
                               'id-RICcontrolStatus': {'type': 'ProtocolIE-ID',
                                                       'value': 24},
                               'id-RICindication': {'type': 'ProcedureCode',
                                                    'value': 5},
                               'id-RICindicationHeader': {'type': 'ProtocolIE-ID',
                                                          'value': 25},
                               'id-RICindicationMessage': {'type': 'ProtocolIE-ID',
                                                           'value': 26},
                               'id-RICindicationSN': {'type': 'ProtocolIE-ID',
                                                      'value': 27},
                               'id-RICindicationType': {'type': 'ProtocolIE-ID',
                                                        'value': 28},
                               'id-RICrequestID': {'type': 'ProtocolIE-ID',
                                                   'value': 29},
                               'id-RICserviceQuery': {'type': 'ProcedureCode',
                                                      'value': 6},
                               'id-RICserviceUpdate': {'type': 'ProcedureCode',
                                                       'value': 7},
                               'id-RICsubscription': {'type': 'ProcedureCode',
                                                      'value': 8},
                               'id-RICsubscription-withCause-Item': {'type': 'ProtocolIE-ID',
                                                                     'value': 61},
                               'id-RICsubscriptionDelete': {'type': 'ProcedureCode',
                                                            'value': 9},
                               'id-RICsubscriptionDeleteRequired': {'type': 'ProcedureCode',
                                                                    'value': 12},
                               'id-RICsubscriptionDetails': {'type': 'ProtocolIE-ID',
                                                             'value': 30},
                               'id-RICsubscriptionToBeRemoved': {'type': 'ProtocolIE-ID',
                                                                 'value': 60},
                               'id-Reset': {'type': 'ProcedureCode',
                                            'value': 3},
                               'id-TNLinformation': {'type': 'ProtocolIE-ID',
                                                     'value': 48},
                               'id-TimeToWait': {'type': 'ProtocolIE-ID',
                                                 'value': 31},
                               'id-TransactionID': {'type': 'ProtocolIE-ID',
                                                    'value': 49},
                               'maxProtocolIEs': {'type': 'INTEGER',
                                                  'value': 65535},
                               'maxnoofErrors': {'type': 'INTEGER',
                                                 'value': 256},
                               'maxofE2nodeComponents': {'type': 'INTEGER',
                                                         'value': 1024},
                               'maxofRANfunctionID': {'type': 'INTEGER',
                                                      'value': 256},
                               'maxofRICactionID': {'type': 'INTEGER',
                                                    'value': 16},
                               'maxofRICrequestID': {'type': 'INTEGER',
                                                     'value': 4294967295},
                               'maxofTNLA': {'type': 'INTEGER', 'value': 32}}}}