EXPECTED = {'E2AP-PDU-Contents': {'extensibility-implied': False,
                       'imports': {'E2AP-Constants': ['id-Cause',
                                                      'id-CriticalityDiagnostics',
                                                      'id-E2connectionFailed-Item',
                                                      'id-E2connectionSetup',
                                                      'id-E2connectionSetupFailed',
                                                      'id-E2connectionSetupFailed-Item',
                                                      'id-E2connectionUpdate-Item',
                                                      'id-E2connectionUpdateAdd',
                                                      'id-E2connectionUpdateModify',
                                                      'id-E2connectionUpdateRemove',
                                                      'id-E2connectionUpdateRemove-Item',
                                                      'id-E2nodeComponentConfigAddition',
                                                      'id-E2nodeComponentConfigAddition-Item',
                                                      'id-E2nodeComponentConfigAdditionAck',
                                                      'id-E2nodeComponentConfigAdditionAck-Item',
                                                      'id-E2nodeComponentConfigRemoval',
                                                      'id-E2nodeComponentConfigRemoval-Item',
                                                      'id-E2nodeComponentConfigRemovalAck',
                                                      'id-E2nodeComponentConfigRemovalAck-Item',
                                                      'id-E2nodeComponentConfigUpdate',
                                                      'id-E2nodeComponentConfigUpdate-Item',
                                                      'id-E2nodeComponentConfigUpdateAck',
                                                      'id-E2nodeComponentConfigUpdateAck-Item',
                                                      'id-E2nodeTNLassociationRemoval',
                                                      'id-E2nodeTNLassociationRemoval-Item',
                                                      'id-GlobalE2node-ID',
                                                      'id-GlobalRIC-ID',
                                                      'id-RANfunction-Item',
                                                      'id-RANfunctionID',
                                                      'id-RANfunctionID-Item',
                                                      'id-RANfunctionIEcause-Item',
                                                      'id-RANfunctionsAccepted',
                                                      'id-RANfunctionsAdded',
                                                      'id-RANfunctionsDeleted',
                                                      'id-RANfunctionsModified',
                                                      'id-RANfunctionsRejected',
                                                      'id-RICaction-Admitted-Item',
                                                      'id-RICaction-NotAdmitted-Item',
                                                      'id-RICaction-ToBeSetup-Item',
                                                      'id-RICactionID',
                                                      'id-RICactions-Admitted',
                                                      'id-RICactions-NotAdmitted',
                                                      'id-RICcallProcessID',
                                                      'id-RICcontrolAckRequest',
                                                      'id-RICcontrolHeader',
                                                      'id-RICcontrolMessage',
                                                      'id-RICcontrolOutcome',
                                                      'id-RICindicationHeader',
                                                      'id-RICindicationMessage',
                                                      'id-RICindicationSN',
                                                      'id-RICindicationType',
                                                      'id-RICrequestID',
                                                      'id-RICserviceQuery',
                                                      'id-RICsubscription-withCause-Item',
                                                      'id-RICsubscriptionDetails',
                                                      'id-RICsubscriptionToBeRemoved',
                                                      'id-TNLinformation',
                                                      'id-TimeToWait',
                                                      'id-TransactionID',
                                                      'maxofE2nodeComponents',
                                                      'maxofRANfunctionID',
                                                      'maxofRICactionID',
                                                      'maxofRICrequestID',
                                                      'maxofTNLA'],
                                   'E2AP-Containers': ['E2AP-PROTOCOL-IES',
                                                       'E2AP-PROTOCOL-IES-PAIR',
                                                       'ProtocolIE-Container',
                                                       'ProtocolIE-ContainerList',
                                                       'ProtocolIE-SingleContainer',
                                                       '{',
                                                       '{',
                                                       '{',
                                                       '}',
                                                       '}',
                                                       '}'],
                                   'E2AP-IEs': ['Cause',
                                                'CriticalityDiagnostics',
                                                'E2nodeComponentConfiguration',
                                                'E2nodeComponentConfigurationAck',
                                                'E2nodeComponentID',
                                                'E2nodeComponentInterfaceType',
                                                'GlobalE2node-ID',
                                                'GlobalRIC-ID',
                                                'RANfunctionDefinition',
                                                'RANfunctionID',
                                                'RANfunctionOID',
                                                'RANfunctionRevision',
                                                'RICactionDefinition',
                                                'RICactionID',
                                                'RICactionType',
                                                'RICcallProcessID',
                                                'RICcontrolAckRequest',
                                                'RICcontrolHeader',
                                                'RICcontrolMessage',
                                                'RICcontrolOutcome',
                                                'RICeventTriggerDefinition',
                                                'RICindicationHeader',
                                                'RICindicationMessage',
                                                'RICindicationSN',
                                                'RICindicationType',
                                                'RICrequestID',
                                                'RICsubsequentAction',
                                                'TNLinformation',
                                                'TNLusage',
                                                'TimeToWait',
                                                'TransactionID']},
                       'object-classes': {},
                       'object-sets': {'E2RemovalFailureIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                               'members': []},
                                       'E2RemovalRequestIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                               'members': []},
                                       'E2RemovalResponseIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                'members': []},
                                       'E2connectionSetupFailed-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                           'members': []},
                                       'E2connectionUpdate-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                  'members': []},
                                       'E2connectionUpdate-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                      'members': []},
                                       'E2connectionUpdateAck-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                     'members': []},
                                       'E2connectionUpdateFailure-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                         'members': []},
                                       'E2connectionUpdateRemove-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                            'members': []},
                                       'E2nodeComponentConfigAddition-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                                 'members': []},
                                       'E2nodeComponentConfigAdditionAck-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                                    'members': []},
                                       'E2nodeComponentConfigRemoval-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                                'members': []},
                                       'E2nodeComponentConfigRemovalAck-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                                   'members': []},
                                       'E2nodeComponentConfigUpdate-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                               'members': []},
                                       'E2nodeComponentConfigUpdateAck-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                                  'members': []},
                                       'E2nodeConfigurationUpdate-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                         'members': []},
                                       'E2nodeConfigurationUpdateAcknowledge-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                                    'members': []},
                                       'E2nodeConfigurationUpdateFailure-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                                'members': []},
                                       'E2nodeTNLassociationRemoval-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                               'members': []},
                                       'E2setupFailureIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                             'members': []},
                                       'E2setupRequestIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                             'members': []},
                                       'E2setupResponseIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                              'members': []},
                                       'ErrorIndication-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                               'members': []},
                                       'RANfunction-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                               'members': []},
                                       'RANfunctionID-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                 'members': []},
                                       'RANfunctionIDcause-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                      'members': []},
                                       'RICaction-Admitted-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                      'members': []},
                                       'RICaction-NotAdmitted-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                         'members': []},
                                       'RICaction-ToBeSetup-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                       'members': []},
                                       'RICcontrolAcknowledge-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                     'members': []},
                                       'RICcontrolFailure-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                 'members': []},
                                       'RICcontrolRequest-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                 'members': []},
                                       'RICindication-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                             'members': []},
                                       'RICserviceQuery-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                               'members': []},
                                       'RICserviceUpdate-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                'members': []},
                                       'RICserviceUpdateAcknowledge-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                           'members': []},
                                       'RICserviceUpdateFailure-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                       'members': []},
                                       'RICsubscription-withCause-ItemIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                             'members': []},
                                       'RICsubscriptionDeleteFailure-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                            'members': []},
                                       'RICsubscriptionDeleteRequest-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                            'members': []},
                                       'RICsubscriptionDeleteRequired-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                             'members': []},
                                       'RICsubscriptionDeleteResponse-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                             'members': []},
                                       'RICsubscriptionFailure-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                      'members': []},
                                       'RICsubscriptionRequest-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                      'members': []},
                                       'RICsubscriptionResponse-IEs': {'class': 'E2AP-PROTOCOL-IES',
                                                                       'members': []},
                                       'ResetRequestIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                           'members': []},
                                       'ResetResponseIEs': {'class': 'E2AP-PROTOCOL-IES',
                                                            'members': []}},
                       'tags': 'AUTOMATIC',
                       'types': {'E2RemovalFailure': {'members': [{'actual-parameters': ['{'],
                                                                   'name': 'protocolIEs',
                                                                   'type': 'ProtocolIE-Container'},
                                                                  None],
                                                      'type': 'SEQUENCE'},
                                 'E2RemovalRequest': {'members': [{'actual-parameters': ['{'],
                                                                   'name': 'protocolIEs',
                                                                   'type': 'ProtocolIE-Container'},
                                                                  None],
                                                      'type': 'SEQUENCE'},
                                 'E2RemovalResponse': {'members': [{'actual-parameters': ['{'],
                                                                    'name': 'protocolIEs',
                                                                    'type': 'ProtocolIE-Container'},
                                                                   None],
                                                       'type': 'SEQUENCE'},
                                 'E2connectionSetupFailed-Item': {'members': [{'name': 'tnlInformation',
                                                                               'type': 'TNLinformation'},
                                                                              {'name': 'cause',
                                                                               'type': 'Cause'},
                                                                              None],
                                                                  'type': 'SEQUENCE'},
                                 'E2connectionSetupFailed-List': {'element': {'actual-parameters': ['{'],
                                                                              'type': 'ProtocolIE-SingleContainer'},
                                                                  'size': [(1,
                                                                            'maxofTNLA')],
                                                                  'type': 'SEQUENCE '
                                                                          'OF'},
                                 'E2connectionUpdate': {'members': [{'actual-parameters': ['{'],
                                                                     'name': 'protocolIEs',
                                                                     'type': 'ProtocolIE-Container'},
                                                                    None],
                                                        'type': 'SEQUENCE'},
                                 'E2connectionUpdate-Item': {'members': [{'name': 'tnlInformation',
                                                                          'type': 'TNLinformation'},
                                                                         {'name': 'tnlUsage',
                                                                          'type': 'TNLusage'},
                                                                         None],
                                                             'type': 'SEQUENCE'},
                                 'E2connectionUpdate-List': {'element': {'actual-parameters': ['{'],
                                                                         'type': 'ProtocolIE-SingleContainer'},
                                                             'size': [(1,
                                                                       'maxofTNLA')],
                                                             'type': 'SEQUENCE '
                                                                     'OF'},
                                 'E2connectionUpdateAcknowledge': {'members': [{'actual-parameters': ['{'],
                                                                                'name': 'protocolIEs',
                                                                                'type': 'ProtocolIE-Container'},
                                                                               None],
                                                                   'type': 'SEQUENCE'},
                                 'E2connectionUpdateFailure': {'members': [{'actual-parameters': ['{'],
                                                                            'name': 'protocolIEs',
                                                                            'type': 'ProtocolIE-Container'},
                                                                           None],
                                                               'type': 'SEQUENCE'},
                                 'E2connectionUpdateRemove-Item': {'members': [{'name': 'tnlInformation',
                                                                                'type': 'TNLinformation'},
                                                                               None],
                                                                   'type': 'SEQUENCE'},
                                 'E2connectionUpdateRemove-List': {'element': {'actual-parameters': ['{'],
                                                                               'type': 'ProtocolIE-SingleContainer'},
                                                                   'size': [(1,
                                                                             'maxofTNLA')],
                                                                   'type': 'SEQUENCE '
                                                                           'OF'},
                                 'E2nodeComponentConfigAddition-Item': {'members': [{'name': 'e2nodeComponentInterfaceType',
                                                                                     'type': 'E2nodeComponentInterfaceType'},
                                                                                    {'name': 'e2nodeComponentID',
                                                                                     'type': 'E2nodeComponentID'},
                                                                                    {'name': 'e2nodeComponentConfiguration',
                                                                                     'type': 'E2nodeComponentConfiguration'},
                                                                                    None],
                                                                        'type': 'SEQUENCE'},
                                 'E2nodeComponentConfigAddition-List': {'element': {'actual-parameters': ['{'],
                                                                                    'type': 'ProtocolIE-SingleContainer'},
                                                                        'size': [(1,
                                                                                  'maxofE2nodeComponents')],
                                                                        'type': 'SEQUENCE '
                                                                                'OF'},
                                 'E2nodeComponentConfigAdditionAck-Item': {'members': [{'name': 'e2nodeComponentInterfaceType',
                                                                                        'type': 'E2nodeComponentInterfaceType'},
                                                                                       {'name': 'e2nodeComponentID',
                                                                                        'type': 'E2nodeComponentID'},
                                                                                       {'name': 'e2nodeComponentConfigurationAck',
                                                                                        'type': 'E2nodeComponentConfigurationAck'},
                                                                                       None],
                                                                           'type': 'SEQUENCE'},
                                 'E2nodeComponentConfigAdditionAck-List': {'element': {'actual-parameters': ['{'],
                                                                                       'type': 'ProtocolIE-SingleContainer'},
                                                                           'size': [(1,
                                                                                     'maxofE2nodeComponents')],
                                                                           'type': 'SEQUENCE '
                                                                                   'OF'},
                                 'E2nodeComponentConfigRemoval-Item': {'members': [{'name': 'e2nodeComponentInterfaceType',
                                                                                    'type': 'E2nodeComponentInterfaceType'},
                                                                                   {'name': 'e2nodeComponentID',
                                                                                    'type': 'E2nodeComponentID'},
                                                                                   None],
                                                                       'type': 'SEQUENCE'},
                                 'E2nodeComponentConfigRemoval-List': {'element': {'actual-parameters': ['{'],
                                                                                   'type': 'ProtocolIE-SingleContainer'},
                                                                       'size': [(1,
                                                                                 'maxofE2nodeComponents')],
                                                                       'type': 'SEQUENCE '
                                                                               'OF'},
                                 'E2nodeComponentConfigRemovalAck-Item': {'members': [{'name': 'e2nodeComponentInterfaceType',
                                                                                       'type': 'E2nodeComponentInterfaceType'},
                                                                                      {'name': 'e2nodeComponentID',
                                                                                       'type': 'E2nodeComponentID'},
                                                                                      {'name': 'e2nodeComponentConfigurationAck',
                                                                                       'type': 'E2nodeComponentConfigurationAck'},
                                                                                      None],
                                                                          'type': 'SEQUENCE'},
                                 'E2nodeComponentConfigRemovalAck-List': {'element': {'actual-parameters': ['{'],
                                                                                      'type': 'ProtocolIE-SingleContainer'},
                                                                          'size': [(1,
                                                                                    'maxofE2nodeComponents')],
                                                                          'type': 'SEQUENCE '
                                                                                  'OF'},
                                 'E2nodeComponentConfigUpdate-Item': {'members': [{'name': 'e2nodeComponentInterfaceType',
                                                                                   'type': 'E2nodeComponentInterfaceType'},
                                                                                  {'name': 'e2nodeComponentID',
                                                                                   'type': 'E2nodeComponentID'},
                                                                                  {'name': 'e2nodeComponentConfiguration',
                                                                                   'type': 'E2nodeComponentConfiguration'},
                                                                                  None],
                                                                      'type': 'SEQUENCE'},
                                 'E2nodeComponentConfigUpdate-List': {'element': {'actual-parameters': ['{'],
                                                                                  'type': 'ProtocolIE-SingleContainer'},
                                                                      'size': [(1,
                                                                                'maxofE2nodeComponents')],
                                                                      'type': 'SEQUENCE '
                                                                              'OF'},
                                 'E2nodeComponentConfigUpdateAck-Item': {'members': [{'name': 'e2nodeComponentInterfaceType',
                                                                                      'type': 'E2nodeComponentInterfaceType'},
                                                                                     {'name': 'e2nodeComponentID',
                                                                                      'type': 'E2nodeComponentID'},
                                                                                     {'name': 'e2nodeComponentConfigurationAck',
                                                                                      'type': 'E2nodeComponentConfigurationAck'},
                                                                                     None],
                                                                         'type': 'SEQUENCE'},
                                 'E2nodeComponentConfigUpdateAck-List': {'element': {'actual-parameters': ['{'],
                                                                                     'type': 'ProtocolIE-SingleContainer'},
                                                                         'size': [(1,
                                                                                   'maxofE2nodeComponents')],
                                                                         'type': 'SEQUENCE '
                                                                                 'OF'},
                                 'E2nodeConfigurationUpdate': {'members': [{'actual-parameters': ['{'],
                                                                            'name': 'protocolIEs',
                                                                            'type': 'ProtocolIE-Container'},
                                                                           None],
                                                               'type': 'SEQUENCE'},
                                 'E2nodeConfigurationUpdateAcknowledge': {'members': [{'actual-parameters': ['{'],
                                                                                       'name': 'protocolIEs',
                                                                                       'type': 'ProtocolIE-Container'},
                                                                                      None],
                                                                          'type': 'SEQUENCE'},
                                 'E2nodeConfigurationUpdateFailure': {'members': [{'actual-parameters': ['{'],
                                                                                   'name': 'protocolIEs',
                                                                                   'type': 'ProtocolIE-Container'},
                                                                                  None],
                                                                      'type': 'SEQUENCE'},
                                 'E2nodeTNLassociationRemoval-Item': {'members': [{'name': 'tnlInformation',
                                                                                   'type': 'TNLinformation'},
                                                                                  {'name': 'tnlInformationRIC',
                                                                                   'type': 'TNLinformation'},
                                                                                  None],
                                                                      'type': 'SEQUENCE'},
                                 'E2nodeTNLassociationRemoval-List': {'element': {'actual-parameters': ['{'],
                                                                                  'type': 'ProtocolIE-SingleContainer'},
                                                                      'size': [(1,
                                                                                'maxofTNLA')],
                                                                      'type': 'SEQUENCE '
                                                                              'OF'},
                                 'E2setupFailure': {'members': [{'actual-parameters': ['{'],
                                                                 'name': 'protocolIEs',
                                                                 'type': 'ProtocolIE-Container'},
                                                                None],
                                                    'type': 'SEQUENCE'},
                                 'E2setupRequest': {'members': [{'actual-parameters': ['{'],
                                                                 'name': 'protocolIEs',
                                                                 'type': 'ProtocolIE-Container'},
                                                                None],
                                                    'type': 'SEQUENCE'},
                                 'E2setupResponse': {'members': [{'actual-parameters': ['{'],
                                                                  'name': 'protocolIEs',
                                                                  'type': 'ProtocolIE-Container'},
                                                                 None],
                                                     'type': 'SEQUENCE'},
                                 'ErrorIndication': {'members': [{'actual-parameters': ['{'],
                                                                  'name': 'protocolIEs',
                                                                  'type': 'ProtocolIE-Container'},
                                                                 None],
                                                     'type': 'SEQUENCE'},
                                 'RANfunction-Item': {'members': [{'name': 'ranFunctionID',
                                                                   'type': 'RANfunctionID'},
                                                                  {'name': 'ranFunctionDefinition',
                                                                   'type': 'RANfunctionDefinition'},
                                                                  {'name': 'ranFunctionRevision',
                                                                   'type': 'RANfunctionRevision'},
                                                                  {'name': 'ranFunctionOID',
                                                                   'type': 'RANfunctionOID'},
                                                                  None],
                                                      'type': 'SEQUENCE'},
                                 'RANfunctionID-Item': {'members': [{'name': 'ranFunctionID',
                                                                     'type': 'RANfunctionID'},
                                                                    {'name': 'ranFunctionRevision',
                                                                     'type': 'RANfunctionRevision'},
                                                                    None],
                                                        'type': 'SEQUENCE'},
                                 'RANfunctionIDcause-Item': {'members': [{'name': 'ranFunctionID',
                                                                          'type': 'RANfunctionID'},
                                                                         {'name': 'cause',
                                                                          'type': 'Cause'},
                                                                         None],
                                                             'type': 'SEQUENCE'},
                                 'RANfunctions-List': {'element': {'actual-parameters': ['{'],
                                                                   'type': 'ProtocolIE-SingleContainer'},
                                                       'size': [(1,
                                                                 'maxofRANfunctionID')],
                                                       'type': 'SEQUENCE OF'},
                                 'RANfunctionsID-List': {'element': {'actual-parameters': ['{'],
                                                                     'type': 'ProtocolIE-SingleContainer'},
                                                         'size': [(1,
                                                                   'maxofRANfunctionID')],
                                                         'type': 'SEQUENCE OF'},
                                 'RANfunctionsIDcause-List': {'element': {'actual-parameters': ['{'],
                                                                          'type': 'ProtocolIE-SingleContainer'},
                                                              'size': [(1,
                                                                        'maxofRANfunctionID')],
                                                              'type': 'SEQUENCE '
                                                                      'OF'},
                                 'RICaction-Admitted-Item': {'members': [{'name': 'ricActionID',
                                                                          'type': 'RICactionID'},
                                                                         None],
                                                             'type': 'SEQUENCE'},
                                 'RICaction-Admitted-List': {'element': {'actual-parameters': ['{'],
                                                                         'type': 'ProtocolIE-SingleContainer'},
                                                             'size': [(1,
                                                                       'maxofRICactionID')],
                                                             'type': 'SEQUENCE '
                                                                     'OF'},
                                 'RICaction-NotAdmitted-Item': {'members': [{'name': 'ricActionID',
                                                                             'type': 'RICactionID'},
                                                                            {'name': 'cause',
                                                                             'type': 'Cause'},
                                                                            None],
                                                                'type': 'SEQUENCE'},
                                 'RICaction-NotAdmitted-List': {'element': {'actual-parameters': ['{'],
                                                                            'type': 'ProtocolIE-SingleContainer'},
                                                                'size': [(0,
                                                                          'maxofRICactionID')],
                                                                'type': 'SEQUENCE '
                                                                        'OF'},
                                 'RICaction-ToBeSetup-Item': {'members': [{'name': 'ricActionID',
                                                                           'type': 'RICactionID'},
                                                                          {'name': 'ricActionType',
                                                                           'type': 'RICactionType'},
                                                                          {'name': 'ricActionDefinition',
                                                                           'optional': True,
                                                                           'type': 'RICactionDefinition'},
                                                                          {'name': 'ricSubsequentAction',
                                                                           'optional': True,
                                                                           'type': 'RICsubsequentAction'},
                                                                          None],
                                                              'type': 'SEQUENCE'},
                                 'RICactions-ToBeSetup-List': {'element': {'actual-parameters': ['{'],
                                                                           'type': 'ProtocolIE-SingleContainer'},
                                                               'size': [(1,
                                                                         'maxofRICactionID')],
                                                               'type': 'SEQUENCE '
                                                                       'OF'},
                                 'RICcontrolAcknowledge': {'members': [{'actual-parameters': ['{'],
                                                                        'name': 'protocolIEs',
                                                                        'type': 'ProtocolIE-Container'},
                                                                       None],
                                                           'type': 'SEQUENCE'},
                                 'RICcontrolFailure': {'members': [{'actual-parameters': ['{'],
                                                                    'name': 'protocolIEs',
                                                                    'type': 'ProtocolIE-Container'},
                                                                   None],
                                                       'type': 'SEQUENCE'},
                                 'RICcontrolRequest': {'members': [{'actual-parameters': ['{'],
                                                                    'name': 'protocolIEs',
                                                                    'type': 'ProtocolIE-Container'},
                                                                   None],
                                                       'type': 'SEQUENCE'},
                                 'RICindication': {'members': [{'actual-parameters': ['{'],
                                                                'name': 'protocolIEs',
                                                                'type': 'ProtocolIE-Container'},
                                                               None],
                                                   'type': 'SEQUENCE'},
                                 'RICserviceQuery': {'members': [{'actual-parameters': ['{'],
                                                                  'name': 'protocolIEs',
                                                                  'type': 'ProtocolIE-Container'},
                                                                 None],
                                                     'type': 'SEQUENCE'},
                                 'RICserviceUpdate': {'members': [{'actual-parameters': ['{'],
                                                                   'name': 'protocolIEs',
                                                                   'type': 'ProtocolIE-Container'},
                                                                  None],
                                                      'type': 'SEQUENCE'},
                                 'RICserviceUpdateAcknowledge': {'members': [{'actual-parameters': ['{'],
                                                                              'name': 'protocolIEs',
                                                                              'type': 'ProtocolIE-Container'},
                                                                             None],
                                                                 'type': 'SEQUENCE'},
                                 'RICserviceUpdateFailure': {'members': [{'actual-parameters': ['{'],
                                                                          'name': 'protocolIEs',
                                                                          'type': 'ProtocolIE-Container'},
                                                                         None],
                                                             'type': 'SEQUENCE'},
                                 'RICsubscription-List-withCause': {'element': {'actual-parameters': ['{'],
                                                                                'type': 'ProtocolIE-SingleContainer'},
                                                                    'size': [(1,
                                                                              'maxofRICrequestID')],
                                                                    'type': 'SEQUENCE '
                                                                            'OF'},
                                 'RICsubscription-withCause-Item': {'members': [{'name': 'ricRequestID',
                                                                                 'type': 'RICrequestID'},
                                                                                {'name': 'ranFunctionID',
                                                                                 'type': 'RANfunctionID'},
                                                                                {'name': 'cause',
                                                                                 'type': 'Cause'},
                                                                                None],
                                                                    'type': 'SEQUENCE'},
                                 'RICsubscriptionDeleteFailure': {'members': [{'actual-parameters': ['{'],
                                                                               'name': 'protocolIEs',
                                                                               'type': 'ProtocolIE-Container'},
                                                                              None],
                                                                  'type': 'SEQUENCE'},
                                 'RICsubscriptionDeleteRequest': {'members': [{'actual-parameters': ['{'],
                                                                               'name': 'protocolIEs',
                                                                               'type': 'ProtocolIE-Container'},
                                                                              None],
                                                                  'type': 'SEQUENCE'},
                                 'RICsubscriptionDeleteRequired': {'members': [{'actual-parameters': ['{'],
                                                                                'name': 'protocolIEs',
                                                                                'type': 'ProtocolIE-Container'},
                                                                               None],
                                                                   'type': 'SEQUENCE'},
                                 'RICsubscriptionDeleteResponse': {'members': [{'actual-parameters': ['{'],
                                                                                'name': 'protocolIEs',
                                                                                'type': 'ProtocolIE-Container'},
                                                                               None],
                                                                   'type': 'SEQUENCE'},
                                 'RICsubscriptionDetails': {'members': [{'name': 'ricEventTriggerDefinition',
                                                                         'type': 'RICeventTriggerDefinition'},
                                                                        {'name': 'ricAction-ToBeSetup-List',
                                                                         'type': 'RICactions-ToBeSetup-List'},
                                                                        None],
                                                            'type': 'SEQUENCE'},
                                 'RICsubscriptionFailure': {'members': [{'actual-parameters': ['{'],
                                                                         'name': 'protocolIEs',
                                                                         'type': 'ProtocolIE-Container'},
                                                                        None],
                                                            'type': 'SEQUENCE'},
                                 'RICsubscriptionRequest': {'members': [{'actual-parameters': ['{'],
                                                                         'name': 'protocolIEs',
                                                                         'type': 'ProtocolIE-Container'},
                                                                        None],
                                                            'type': 'SEQUENCE'},
                                 'RICsubscriptionResponse': {'members': [{'actual-parameters': ['{'],
                                                                          'name': 'protocolIEs',
                                                                          'type': 'ProtocolIE-Container'},
                                                                         None],
                                                             'type': 'SEQUENCE'},
                                 'ResetRequest': {'members': [{'actual-parameters': ['{'],
                                                               'name': 'protocolIEs',
                                                               'type': 'ProtocolIE-Container'},
                                                              None],
                                                  'type': 'SEQUENCE'},
                                 'ResetResponse': {'members': [{'actual-parameters': ['{'],
                                                                'name': 'protocolIEs',
                                                                'type': 'ProtocolIE-Container'},
                                                               None],
                                                   'type': 'SEQUENCE'}},
                       'values': {}}}