EXPECTED = {'E2AP-Containers': {'extensibility-implied': False,
                     'imports': {'E2AP-CommonDataTypes': ['Criticality',
                                                          'Presence',
                                                          'ProtocolIE-ID'],
                                 'E2AP-Constants': ['maxProtocolIEs']},
                     'object-classes': {'E2AP-PROTOCOL-IES': {'members': [{'name': '&id',
                                                                           'type': 'ProtocolIE-ID'},
                                                                          {'name': '&criticality',
                                                                           'type': 'Criticality'},
                                                                          {'name': '&Value',
                                                                           'type': 'OpenType'},
                                                                          {'name': '&presence',
                                                                           'type': 'Presence'}]},
                                        'E2AP-PROTOCOL-IES-PAIR': {'members': [{'name': '&id',
                                                                                'type': 'ProtocolIE-ID'},
                                                                               {'name': '&firstCriticality',
                                                                                'type': 'Criticality'},
                                                                               {'name': '&FirstValue',
                                                                                'type': 'OpenType'},
                                                                               {'name': '&secondCriticality',
                                                                                'type': 'Criticality'},
                                                                               {'name': '&SecondValue',
                                                                                'type': 'OpenType'},
                                                                               {'name': '&presence',
                                                                                'type': 'Presence'}]}},
                     'object-sets': {},
                     'tags': 'AUTOMATIC',
                     'types': {'ProtocolIE-Container': {'element': {'actual-parameters': ['{'],
                                                                    'type': 'ProtocolIE-Field'},
                                                        'parameters': ['IEsSetParam'],
                                                        'size': [(0,
                                                                  'maxProtocolIEs')],
                                                        'type': 'SEQUENCE OF'},
                               'ProtocolIE-ContainerList': {'element': {'actual-parameters': ['{'],
                                                                        'type': 'ProtocolIE-SingleContainer'},
                                                            'parameters': ['lowerBound',
                                                                           'upperBound',
                                                                           'IEsSetParam'],
                                                            'size': [('lowerBound',
                                                                      'upperBound')],
                                                            'type': 'SEQUENCE '
                                                                    'OF'},
                               'ProtocolIE-ContainerPair': {'element': {'actual-parameters': ['{'],
                                                                        'type': 'ProtocolIE-FieldPair'},
                                                            'parameters': ['IEsSetParam'],
                                                            'size': [(0,
                                                                      'maxProtocolIEs')],
                                                            'type': 'SEQUENCE '
                                                                    'OF'},
                               'ProtocolIE-ContainerPairList': {'element': {'actual-parameters': ['{'],
                                                                            'type': 'ProtocolIE-ContainerPair'},
                                                                'parameters': ['lowerBound',
                                                                               'upperBound',
                                                                               'IEsSetParam'],
                                                                'size': [('lowerBound',
                                                                          'upperBound')],
                                                                'type': 'SEQUENCE '
                                                                        'OF'},
                               'ProtocolIE-Field': {'members': [{'name': 'id',
                                                                 'table': {'type': 'IEsSetParam'},
                                                                 'type': 'E2AP-PROTOCOL-IES.&id'},
                                                                {'name': 'criticality',
                                                                 'table': ['IEsSetParam',
                                                                           ['id']],
                                                                 'type': 'E2AP-PROTOCOL-IES.&criticality'},
                                                                {'name': 'value',
                                                                 'table': ['IEsSetParam',
                                                                           ['id']],
                                                                 'type': 'E2AP-PROTOCOL-IES.&Value'}],
                                                    'parameters': ['IEsSetParam'],
                                                    'type': 'SEQUENCE'},
                               'ProtocolIE-FieldPair': {'members': [{'name': 'id',
                                                                     'table': {'type': 'IEsSetParam'},
                                                                     'type': 'E2AP-PROTOCOL-IES-PAIR.&id'},
                                                                    {'name': 'firstCriticality',
                                                                     'table': ['IEsSetParam',
                                                                               ['id']],
                                                                     'type': 'E2AP-PROTOCOL-IES-PAIR.&firstCriticality'},
                                                                    {'name': 'firstValue',
                                                                     'table': ['IEsSetParam',
                                                                               ['id']],
                                                                     'type': 'E2AP-PROTOCOL-IES-PAIR.&FirstValue'},
                                                                    {'name': 'secondCriticality',
                                                                     'table': ['IEsSetParam',
                                                                               ['id']],
                                                                     'type': 'E2AP-PROTOCOL-IES-PAIR.&secondCriticality'},
                                                                    {'name': 'secondValue',
                                                                     'table': ['IEsSetParam',
                                                                               ['id']],
                                                                     'type': 'E2AP-PROTOCOL-IES-PAIR.&SecondValue'}],
                                                        'parameters': ['IEsSetParam'],
                                                        'type': 'SEQUENCE'},
                               'ProtocolIE-SingleContainer': {'actual-parameters': ['{'],
                                                              'parameters': ['IEsSetParam'],
                                                              'type': 'ProtocolIE-Field'}},
                     'values': {}}}