EXPECTED = {'E2AP-CommonDataTypes': {'extensibility-implied': False,
                          'imports': {},
                          'object-classes': {},
                          'object-sets': {},
                          'tags': 'AUTOMATIC',
                          'types': {'Criticality': {'type': 'ENUMERATED',
                                                    'values': [('reject', 0),
                                                               ('ignore', 1),
                                                               ('notify', 2)]},
                                    'Presence': {'type': 'ENUMERATED',
                                                 'values': [('optional', 0),
                                                            ('conditional', 1),
                                                            ('mandatory', 2)]},
                                    'ProcedureCode': {'restricted-to': [(0,
                                                                         255)],
                                                      'type': 'INTEGER'},
                                    'ProtocolIE-ID': {'restricted-to': [(0,
                                                                         65535)],
                                                      'type': 'INTEGER'},
                                    'TriggeringMessage': {'type': 'ENUMERATED',
                                                          'values': [('initiating-message',
                                                                      0),
                                                                     ('successful-outcome',
                                                                      1),
                                                                     ('unsuccessfull-outcome',
                                                                      2)]}},
                          'values': {}}}