EXPECTED = {'F1AP-PDU-Contents': {'extensibility-implied': False,
                       'imports': {'F1AP-Constants': ['id-Broadcast-To-Be-Cancelled-Item',
                                                      'id-Broadcast-To-Be-Cancelled-List',
                                                      'id-C-RNTI',
                                                      'id-CUtoDURRCInformation',
                                                      'id-Cancel-all-Warning-Messages-Indicator',
                                                      'id-Candidate-SpCell-Item',
                                                      'id-Candidate-SpCell-List',
                                                      'id-Cause',
                                                      'id-Cells-Broadcast-Cancelled-Item',
                                                      'id-Cells-Broadcast-Cancelled-List',
                                                      'id-Cells-Broadcast-Completed-Item',
                                                      'id-Cells-Broadcast-Completed-List',
                                                      'id-Cells-Failed-to-be-Activated-List',
                                                      'id-Cells-Failed-to-be-Activated-List-Item',
                                                      'id-Cells-Status-Item',
                                                      'id-Cells-Status-List',
                                                      'id-Cells-To-Be-Broadcast-Item',
                                                      'id-Cells-To-Be-Broadcast-List',
                                                      'id-Cells-to-be-Activated-List',
                                                      'id-Cells-to-be-Activated-List-Item',
                                                      'id-Cells-to-be-Barred-Item',
                                                      'id-Cells-to-be-Barred-List',
                                                      'id-Cells-to-be-Deactivated-List',
                                                      'id-Cells-to-be-Deactivated-List-Item',
                                                      'id-ConfirmedUEID',
                                                      'id-CriticalityDiagnostics',
                                                      'id-DRB-Activity-Item',
                                                      'id-DRB-Activity-List',
                                                      'id-DRB-Notify-Item',
                                                      'id-DRB-Notify-List',
                                                      'id-DRBs-FailedToBeModified-Item',
                                                      'id-DRBs-FailedToBeModified-List',
                                                      'id-DRBs-FailedToBeSetup-Item',
                                                      'id-DRBs-FailedToBeSetup-List',
                                                      'id-DRBs-FailedToBeSetupMod-Item',
                                                      'id-DRBs-FailedToBeSetupMod-List',
                                                      'id-DRBs-Modified-Item',
                                                      'id-DRBs-Modified-List',
                                                      'id-DRBs-ModifiedConf-Item',
                                                      'id-DRBs-ModifiedConf-List',
                                                      'id-DRBs-Required-ToBeModified-Item',
                                                      'id-DRBs-Required-ToBeModified-List',
                                                      'id-DRBs-Required-ToBeReleased-Item',
                                                      'id-DRBs-Required-ToBeReleased-List',
                                                      'id-DRBs-Setup-Item',
                                                      'id-DRBs-Setup-List',
                                                      'id-DRBs-SetupMod-Item',
                                                      'id-DRBs-SetupMod-List',
                                                      'id-DRBs-ToBeModified-Item',
                                                      'id-DRBs-ToBeModified-List',
                                                      'id-DRBs-ToBeReleased-Item',
                                                      'id-DRBs-ToBeReleased-List',
                                                      'id-DRBs-ToBeSetup-Item',
                                                      'id-DRBs-ToBeSetup-List',
                                                      'id-DRBs-ToBeSetupMod-Item',
                                                      'id-DRBs-ToBeSetupMod-List',
                                                      'id-DRXConfigurationIndicator',
                                                      'id-DRXCycle',
                                                      'id-DUtoCURRCContainer',
                                                      'id-DUtoCURRCInformation',
                                                      'id-EUTRA-NR-CellResourceCoordinationReq-Container',
                                                      'id-EUTRA-NR-CellResourceCoordinationReqAck-Container',
                                                      'id-ExecuteDuplication',
                                                      'id-FullConfiguration',
                                                      'id-GNB-CU-RRC-Version',
                                                      'id-GNB-CU-TNL-Association-Failed-To-Setup-Item',
                                                      'id-GNB-CU-TNL-Association-Failed-To-Setup-List',
                                                      'id-GNB-CU-TNL-Association-Setup-Item',
                                                      'id-GNB-CU-TNL-Association-Setup-List',
                                                      'id-GNB-CU-TNL-Association-To-Add-Item',
                                                      'id-GNB-CU-TNL-Association-To-Add-List',
                                                      'id-GNB-CU-TNL-Association-To-Remove-Item',
                                                      'id-GNB-CU-TNL-Association-To-Remove-List',
                                                      'id-GNB-CU-TNL-Association-To-Update-Item',
                                                      'id-GNB-CU-TNL-Association-To-Update-List',
                                                      'id-GNB-DU-RRC-Version',
                                                      'id-GNB-DU-Served-Cells-Item',
                                                      'id-GNB-DU-UE-AMBR-UL',
                                                      'id-GNB-DUConfigurationQuery',
                                                      'id-GNBDUOverloadInformation',
                                                      'id-InactivityMonitoringRequest',
                                                      'id-InactivityMonitoringResponse',
                                                      'id-MaskedIMEISV',
                                                      'id-NR-CGI-List-For-Restart-Item',
                                                      'id-NR-CGI-List-For-Restart-List',
                                                      'id-NRCGI',
                                                      'id-NumberofBroadcastRequest',
                                                      'id-PWS-Failed-NR-CGI-Item',
                                                      'id-PWS-Failed-NR-CGI-List',
                                                      'id-PWSSystemInformation',
                                                      'id-PagingCell-Item',
                                                      'id-PagingCell-List',
                                                      'id-PagingDRX',
                                                      'id-PagingIdentity',
                                                      'id-PagingPriority',
                                                      'id-Potential-SpCell-Item',
                                                      'id-Potential-SpCell-List',
                                                      'id-Protected-EUTRA-Resources-Item',
                                                      'id-Protected-EUTRA-Resources-List',
                                                      'id-RAT-FrequencyPriorityInformation',
                                                      'id-RLCFailureIndication',
                                                      'id-RRCContainer',
                                                      'id-RRCRconfigurationCompleteIndicator',
                                                      'id-RepetitionPeriod',
                                                      'id-RequestType',
                                                      'id-ResetType',
                                                      'id-ResourceCoordinationTransferContainer',
                                                      'id-SCell-FailedtoSetup-Item',
                                                      'id-SCell-FailedtoSetup-List',
                                                      'id-SCell-FailedtoSetupMod-Item',
                                                      'id-SCell-FailedtoSetupMod-List',
                                                      'id-SCell-ToBeRemoved-Item',
                                                      'id-SCell-ToBeRemoved-List',
                                                      'id-SCell-ToBeSetup-Item',
                                                      'id-SCell-ToBeSetup-List',
                                                      'id-SCell-ToBeSetupMod-Item',
                                                      'id-SCell-ToBeSetupMod-List',
                                                      'id-SItype-List',
                                                      'id-SRBID',
                                                      'id-SRBs-FailedToBeSetup-Item',
                                                      'id-SRBs-FailedToBeSetup-List',
                                                      'id-SRBs-FailedToBeSetupMod-Item',
                                                      'id-SRBs-FailedToBeSetupMod-List',
                                                      'id-SRBs-Required-ToBeReleased-Item',
                                                      'id-SRBs-Required-ToBeReleased-List',
                                                      'id-SRBs-ToBeReleased-Item',
                                                      'id-SRBs-ToBeReleased-List',
                                                      'id-SRBs-ToBeSetup-Item',
                                                      'id-SRBs-ToBeSetup-List',
                                                      'id-SRBs-ToBeSetupMod-Item',
                                                      'id-SRBs-ToBeSetupMod-List',
                                                      'id-SULAccessIndication',
                                                      'id-ServCellndex',
                                                      'id-Served-Cells-To-Add-Item',
                                                      'id-Served-Cells-To-Add-List',
                                                      'id-Served-Cells-To-Delete-Item',
                                                      'id-Served-Cells-To-Delete-List',
                                                      'id-Served-Cells-To-Modify-Item',
                                                      'id-Served-Cells-To-Modify-List',
                                                      'id-ServingPLMN',
                                                      'id-SpCell-ID',
                                                      'id-SpCellULConfigured',
                                                      'id-TimeToWait',
                                                      'id-TransactionID',
                                                      'id-TransmissionStopIndicator',
                                                      'id-UE-associatedLogicalF1-ConnectionItem',
                                                      'id-UE-associatedLogicalF1-ConnectionListResAck',
                                                      'id-UEIdentityIndexValue',
                                                      'id-UplinkTxDirectCurrentListInformation',
                                                      'id-gNB-CU-Name',
                                                      'id-gNB-CU-UE-F1AP-ID',
                                                      'id-gNB-DU-ID',
                                                      'id-gNB-DU-Name',
                                                      'id-gNB-DU-Served-Cells-List',
                                                      'id-gNB-DU-UE-F1AP-ID',
                                                      'id-oldgNB-DU-UE-F1AP-ID',
                                                      'maxCellineNB',
                                                      'maxCellingNBDU',
                                                      'maxnoofCandidateSpCells',
                                                      'maxnoofDRBs',
                                                      'maxnoofErrors',
                                                      'maxnoofIndividualF1ConnectionsToReset',
                                                      'maxnoofPagingCells',
                                                      'maxnoofPotentialSpCells',
                                                      'maxnoofSCells',
                                                      'maxnoofSRBs',
                                                      'maxnoofTNLAssociations'],
                                   'F1AP-Containers': ['F1AP-PRIVATE-IES',
                                                       'F1AP-PROTOCOL-EXTENSION',
                                                       'F1AP-PROTOCOL-IES',
                                                       'F1AP-PROTOCOL-IES-PAIR',
                                                       'PrivateIE-Container',
                                                       'ProtocolExtensionContainer',
                                                       'ProtocolIE-Container',
                                                       'ProtocolIE-ContainerPair',
                                                       'ProtocolIE-SingleContainer',
                                                       '{',
                                                       '{',
                                                       '{',
                                                       '{',
                                                       '{',
                                                       '}',
                                                       '}',
                                                       '}',
                                                       '}',
                                                       '}'],
                                   'F1AP-IEs': ['BitRate',
                                                'Broadcast-To-Be-Cancelled-Item',
                                                'C-RNTI',
                                                'CUtoDURRCInformation',
                                                'Cancel-all-Warning-Messages-Indicator',
                                                'Candidate-SpCell-Item',
                                                'Cause',
                                                'CellULConfigured',
                                                'Cells-Broadcast-Cancelled-Item',
                                                'Cells-Broadcast-Completed-Item',
                                                'Cells-Failed-to-be-Activated-List-Item',
                                                'Cells-Status-Item',
                                                'Cells-To-Be-Broadcast-Item',
                                                'Cells-to-be-Activated-List-Item',
                                                'Cells-to-be-Barred-Item',
                                                'Cells-to-be-Deactivated-List-Item',
                                                'CriticalityDiagnostics',
                                                'DRB-Activity-Item',
                                                'DRB-Notify-Item',
                                                'DRBID',
                                                'DRBs-FailedToBeModified-Item',
                                                'DRBs-FailedToBeSetup-Item',
                                                'DRBs-FailedToBeSetupMod-Item',
                                                'DRBs-Modified-Item',
                                                'DRBs-ModifiedConf-Item',
                                                'DRBs-Required-ToBeModified-Item',
                                                'DRBs-Required-ToBeReleased-Item',
                                                'DRBs-Setup-Item',
                                                'DRBs-SetupMod-Item',
                                                'DRBs-ToBeModified-Item',
                                                'DRBs-ToBeReleased-Item',
                                                'DRBs-ToBeSetup-Item',
                                                'DRBs-ToBeSetupMod-Item',
                                                'DRXConfigurationIndicator',
                                                'DRXCycle',
                                                'DUtoCURRCContainer',
                                                'DUtoCURRCInformation',
                                                'EUTRA-NR-CellResourceCoordinationReq-Container',
                                                'EUTRA-NR-CellResourceCoordinationReqAck-Container',
                                                'EUTRANQoS',
                                                'ExecuteDuplication',
                                                'FullConfiguration',
                                                'GNB-CU-Name',
                                                'GNB-CU-TNL-Association-Failed-To-Setup-Item',
                                                'GNB-CU-TNL-Association-Setup-Item',
                                                'GNB-CU-TNL-Association-To-Add-Item',
                                                'GNB-CU-TNL-Association-To-Remove-Item',
                                                'GNB-CU-TNL-Association-To-Update-Item',
                                                'GNB-CU-UE-F1AP-ID',
                                                'GNB-DU-ID',
                                                'GNB-DU-Name',
                                                'GNB-DU-Served-Cells-Item',
                                                'GNB-DU-System-Information',
                                                'GNB-DU-UE-F1AP-ID',
                                                'GNB-DUConfigurationQuery',
                                                'GNBDUOverloadInformation',
                                                'InactivityMonitoringRequest',
                                                'InactivityMonitoringResponse',
                                                'MaskedIMEISV',
                                                'NR-CGI-List-For-Restart-Item',
                                                'NRCGI',
                                                'NRPCI',
                                                'NotificationControl',
                                                'NumberofBroadcastRequest',
                                                'PLMN-Identity',
                                                'PWS-Failed-NR-CGI-Item',
                                                'PWSSystemInformation',
                                                'PagingCell-Item',
                                                'PagingDRX',
                                                'PagingIdentity',
                                                'PagingPriority',
                                                'Potential-SpCell-Item',
                                                'Protected-EUTRA-Resources-Item',
                                                'RAT-FrequencyPriorityInformation',
                                                'RLCFailureIndication',
                                                'RRC-Version',
                                                'RRCContainer',
                                                'RRCRconfigurationCompleteIndicator',
                                                'RepetitionPeriod',
                                                'RequestType',
                                                'ResourceCoordinationTransferContainer',
                                                'SCell-FailedtoSetup-Item',
                                                'SCell-FailedtoSetupMod-Item',
                                                'SCell-ToBeRemoved-Item',
                                                'SCell-ToBeSetup-Item',
                                                'SCell-ToBeSetupMod-Item',
                                                'SCellIndex',
                                                'SItype-List',
                                                'SRBID',
                                                'SRBs-FailedToBeSetup-Item',
                                                'SRBs-FailedToBeSetupMod-Item',
                                                'SRBs-Required-ToBeReleased-Item',
                                                'SRBs-ToBeReleased-Item',
                                                'SRBs-ToBeSetup-Item',
                                                'SRBs-ToBeSetupMod-Item',
                                                'SULAccessIndication',
                                                'ServCellIndex',
                                                'Served-Cell-Information',
                                                'Served-Cells-To-Add-Item',
                                                'Served-Cells-To-Delete-Item',
                                                'Served-Cells-To-Modify-Item',
                                                'TimeToWait',
                                                'TransactionID',
                                                'TransmissionStopIndicator',
                                                'UE-associatedLogicalF1-ConnectionItem',
                                                'UEIdentityIndexValue',
                                                'UplinkTxDirectCurrentListInformation']},
                       'object-classes': {},
                       'object-sets': {'Broadcast-To-Be-Cancelled-List-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                  'members': []},
                                       'Candidate-SpCell-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                    'members': []},
                                       'Cells-Broadcast-Cancelled-List-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                  'members': []},
                                       'Cells-Broadcast-Completed-List-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                  'members': []},
                                       'Cells-Failed-to-be-Activated-List-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                     'members': []},
                                       'Cells-Status-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                'members': []},
                                       'Cells-To-Be-Broadcast-List-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                              'members': []},
                                       'Cells-to-be-Activated-List-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                              'members': []},
                                       'Cells-to-be-Barred-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                      'members': []},
                                       'Cells-to-be-Deactivated-List-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                'members': []},
                                       'DLRRCMessageTransferIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                   'members': []},
                                       'DRB-Activity-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                'members': []},
                                       'DRB-Notify-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                              'members': []},
                                       'DRBs-FailedToBeModified-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                           'members': []},
                                       'DRBs-FailedToBeSetup-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                        'members': []},
                                       'DRBs-FailedToBeSetupMod-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                           'members': []},
                                       'DRBs-Modified-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                 'members': []},
                                       'DRBs-ModifiedConf-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                     'members': []},
                                       'DRBs-Required-ToBeModified-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                              'members': []},
                                       'DRBs-Required-ToBeReleased-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                              'members': []},
                                       'DRBs-Setup-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                              'members': []},
                                       'DRBs-SetupMod-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                 'members': []},
                                       'DRBs-ToBeModified-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                     'members': []},
                                       'DRBs-ToBeReleased-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                     'members': []},
                                       'DRBs-ToBeSetup-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                  'members': []},
                                       'DRBs-ToBeSetupMod-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                     'members': []},
                                       'ErrorIndicationIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                              'members': []},
                                       'F1SetupFailureIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                             'members': []},
                                       'F1SetupRequestIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                             'members': []},
                                       'F1SetupResponseIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                              'members': []},
                                       'GNB-CU-TNL-Association-Failed-To-Setup-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                          'members': []},
                                       'GNB-CU-TNL-Association-Setup-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                'members': []},
                                       'GNB-CU-TNL-Association-To-Add-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                 'members': []},
                                       'GNB-CU-TNL-Association-To-Remove-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                    'members': []},
                                       'GNB-CU-TNL-Association-To-Update-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                    'members': []},
                                       'GNB-DU-Served-Cells-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                       'members': []},
                                       'GNBCUConfigurationUpdateAcknowledgeIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                  'members': []},
                                       'GNBCUConfigurationUpdateFailureIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                              'members': []},
                                       'GNBCUConfigurationUpdateIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                       'members': []},
                                       'GNBDUConfigurationUpdateAcknowledgeIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                  'members': []},
                                       'GNBDUConfigurationUpdateFailureIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                              'members': []},
                                       'GNBDUConfigurationUpdateIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                       'members': []},
                                       'GNBDUResourceCoordinationRequest-IEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                'members': []},
                                       'GNBDUResourceCoordinationResponse-IEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                 'members': []},
                                       'GNBDUStatusIndicationIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                    'members': []},
                                       'InitialULRRCMessageTransferIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                          'members': []},
                                       'NR-CGI-List-For-Restart-List-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                                'members': []},
                                       'NotifyIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                     'members': []},
                                       'PWS-Failed-NR-CGI-List-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                          'members': []},
                                       'PWSCancelRequestIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                               'members': []},
                                       'PWSCancelResponseIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                'members': []},
                                       'PWSFailureIndicationIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                   'members': []},
                                       'PWSRestartIndicationIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                   'members': []},
                                       'PagingCell-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                              'members': []},
                                       'PagingIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                     'members': []},
                                       'Potential-SpCell-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                    'members': []},
                                       'PrivateMessage-IEs': {'class': 'F1AP-PRIVATE-IES',
                                                              'members': ['.']},
                                       'Protected-EUTRA-Resources-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                             'members': []},
                                       'ResetAcknowledgeIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                               'members': []},
                                       'ResetIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                    'members': []},
                                       'ResetType-ExtIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                            'members': ['.']},
                                       'SCell-FailedtoSetup-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                       'members': []},
                                       'SCell-FailedtoSetupMod-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                          'members': []},
                                       'SCell-ToBeRemoved-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                     'members': []},
                                       'SCell-ToBeSetup-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                   'members': []},
                                       'SCell-ToBeSetupMod-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                      'members': []},
                                       'SRBs-FailedToBeSetup-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                        'members': []},
                                       'SRBs-FailedToBeSetupMod-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                           'members': []},
                                       'SRBs-Required-ToBeReleased-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                              'members': []},
                                       'SRBs-ToBeReleased-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                     'members': []},
                                       'SRBs-ToBeSetup-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                  'members': []},
                                       'SRBs-ToBeSetupMod-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                     'members': []},
                                       'Served-Cells-To-Add-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                       'members': []},
                                       'Served-Cells-To-Delete-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                          'members': []},
                                       'Served-Cells-To-Modify-ItemIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                          'members': []},
                                       'SystemInformationDeliveryCommandIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                               'members': []},
                                       'UE-associatedLogicalF1-ConnectionItemRes': {'class': 'F1AP-PROTOCOL-IES',
                                                                                    'members': []},
                                       'UE-associatedLogicalF1-ConnectionItemResAck': {'class': 'F1AP-PROTOCOL-IES',
                                                                                       'members': []},
                                       'UEContextModificationConfirmIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                           'members': []},
                                       'UEContextModificationFailureIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                           'members': []},
                                       'UEContextModificationRequestIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                           'members': []},
                                       'UEContextModificationRequiredIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                            'members': []},
                                       'UEContextModificationResponseIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                            'members': []},
                                       'UEContextReleaseCommandIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                      'members': []},
                                       'UEContextReleaseCompleteIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                       'members': []},
                                       'UEContextReleaseRequestIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                      'members': []},
                                       'UEContextSetupFailureIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                    'members': []},
                                       'UEContextSetupRequestIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                    'members': []},
                                       'UEContextSetupResponseIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                     'members': []},
                                       'UEInactivityNotificationIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                       'members': []},
                                       'ULRRCMessageTransferIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                   'members': []},
                                       'WriteReplaceWarningRequestIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                         'members': []},
                                       'WriteReplaceWarningResponseIEs': {'class': 'F1AP-PROTOCOL-IES',
                                                                          'members': []}},
                       'tags': 'AUTOMATIC',
                       'types': {'Broadcast-To-Be-Cancelled-List': {'element': {'actual-parameters': ['{'],
                                                                                'type': 'ProtocolIE-SingleContainer'},
                                                                    'size': [(1,
                                                                              'maxCellingNBDU')],
                                                                    'type': 'SEQUENCE '
                                                                            'OF'},
                                 'Candidate-SpCell-List': {'element': {'actual-parameters': ['{'],
                                                                       'type': 'ProtocolIE-SingleContainer'},
                                                           'size': [(1,
                                                                     'maxnoofCandidateSpCells')],
                                                           'type': 'SEQUENCE '
                                                                   'OF'},
                                 'Cells-Broadcast-Cancelled-List': {'element': {'actual-parameters': ['{'],
                                                                                'type': 'ProtocolIE-SingleContainer'},
                                                                    'size': [(1,
                                                                              'maxCellingNBDU')],
                                                                    'type': 'SEQUENCE '
                                                                            'OF'},
                                 'Cells-Broadcast-Completed-List': {'element': {'actual-parameters': ['{'],
                                                                                'type': 'ProtocolIE-SingleContainer'},
                                                                    'size': [(1,
                                                                              'maxCellingNBDU')],
                                                                    'type': 'SEQUENCE '
                                                                            'OF'},
                                 'Cells-Failed-to-be-Activated-List': {'element': {'actual-parameters': ['{'],
                                                                                   'type': 'ProtocolIE-SingleContainer'},
                                                                       'size': [(1,
                                                                                 'maxCellingNBDU')],
                                                                       'type': 'SEQUENCE '
                                                                               'OF'},
                                 'Cells-Status-List': {'element': {'actual-parameters': ['{'],
                                                                   'type': 'ProtocolIE-SingleContainer'},
                                                       'size': [(0,
                                                                 'maxCellingNBDU')],
                                                       'type': 'SEQUENCE OF'},
                                 'Cells-To-Be-Broadcast-List': {'element': {'actual-parameters': ['{'],
                                                                            'type': 'ProtocolIE-SingleContainer'},
                                                                'size': [(1,
                                                                          'maxCellingNBDU')],
                                                                'type': 'SEQUENCE '
                                                                        'OF'},
                                 'Cells-to-be-Activated-List': {'element': {'actual-parameters': ['{'],
                                                                            'type': 'ProtocolIE-SingleContainer'},
                                                                'size': [(1,
                                                                          'maxCellingNBDU')],
                                                                'type': 'SEQUENCE '
                                                                        'OF'},
                                 'Cells-to-be-Barred-List': {'element': {'actual-parameters': ['{'],
                                                                         'type': 'ProtocolIE-SingleContainer'},
                                                             'size': [(1,
                                                                       'maxCellingNBDU')],
                                                             'type': 'SEQUENCE '
                                                                     'OF'},
                                 'Cells-to-be-Deactivated-List': {'element': {'actual-parameters': ['{'],
                                                                              'type': 'ProtocolIE-SingleContainer'},
                                                                  'size': [(1,
                                                                            'maxCellingNBDU')],
                                                                  'type': 'SEQUENCE '
                                                                          'OF'},
                                 'DLRRCMessageTransfer': {'members': [{'actual-parameters': ['{'],
                                                                       'name': 'protocolIEs',
                                                                       'type': 'ProtocolIE-Container'},
                                                                      None],
                                                          'type': 'SEQUENCE'},
                                 'DRB-Activity-List': {'element': {'actual-parameters': ['{'],
                                                                   'type': 'ProtocolIE-SingleContainer'},
                                                       'size': [(1,
                                                                 'maxnoofDRBs')],
                                                       'type': 'SEQUENCE OF'},
                                 'DRB-Notify-List': {'element': {'actual-parameters': ['{'],
                                                                 'type': 'ProtocolIE-SingleContainer'},
                                                     'size': [1],
                                                     'type': 'SEQUENCE OF'},
                                 'DRBs-FailedToBeModified-List': {'element': {'actual-parameters': ['{'],
                                                                              'type': 'ProtocolIE-SingleContainer'},
                                                                  'size': [(1,
                                                                            'maxnoofDRBs')],
                                                                  'type': 'SEQUENCE '
                                                                          'OF'},
                                 'DRBs-FailedToBeSetup-List': {'element': {'actual-parameters': ['{'],
                                                                           'type': 'ProtocolIE-SingleContainer'},
                                                               'size': [(1,
                                                                         'maxnoofDRBs')],
                                                               'type': 'SEQUENCE '
                                                                       'OF'},
                                 'DRBs-FailedToBeSetupMod-List': {'element': {'actual-parameters': ['{'],
                                                                              'type': 'ProtocolIE-SingleContainer'},
                                                                  'size': [(1,
                                                                            'maxnoofDRBs')],
                                                                  'type': 'SEQUENCE '
                                                                          'OF'},
                                 'DRBs-Modified-List': {'element': {'actual-parameters': ['{'],
                                                                    'type': 'ProtocolIE-SingleContainer'},
                                                        'size': [(1,
                                                                  'maxnoofDRBs')],
                                                        'type': 'SEQUENCE OF'},
                                 'DRBs-ModifiedConf-List': {'element': {'actual-parameters': ['{'],
                                                                        'type': 'ProtocolIE-SingleContainer'},
                                                            'size': [(1,
                                                                      'maxnoofDRBs')],
                                                            'type': 'SEQUENCE '
                                                                    'OF'},
                                 'DRBs-Required-ToBeModified-List': {'element': {'actual-parameters': ['{'],
                                                                                 'type': 'ProtocolIE-SingleContainer'},
                                                                     'size': [(1,
                                                                               'maxnoofDRBs')],
                                                                     'type': 'SEQUENCE '
                                                                             'OF'},
                                 'DRBs-Required-ToBeReleased-List': {'element': {'actual-parameters': ['{'],
                                                                                 'type': 'ProtocolIE-SingleContainer'},
                                                                     'size': [(1,
                                                                               'maxnoofDRBs')],
                                                                     'type': 'SEQUENCE '
                                                                             'OF'},
                                 'DRBs-Setup-List': {'element': {'actual-parameters': ['{'],
                                                                 'type': 'ProtocolIE-SingleContainer'},
                                                     'size': [(1,
                                                               'maxnoofDRBs')],
                                                     'type': 'SEQUENCE OF'},
                                 'DRBs-SetupMod-List': {'element': {'actual-parameters': ['{'],
                                                                    'type': 'ProtocolIE-SingleContainer'},
                                                        'size': [(1,
                                                                  'maxnoofDRBs')],
                                                        'type': 'SEQUENCE OF'},
                                 'DRBs-ToBeModified-List': {'element': {'actual-parameters': ['{'],
                                                                        'type': 'ProtocolIE-SingleContainer'},
                                                            'size': [(1,
                                                                      'maxnoofDRBs')],
                                                            'type': 'SEQUENCE '
                                                                    'OF'},
                                 'DRBs-ToBeReleased-List': {'element': {'actual-parameters': ['{'],
                                                                        'type': 'ProtocolIE-SingleContainer'},
                                                            'size': [(1,
                                                                      'maxnoofDRBs')],
                                                            'type': 'SEQUENCE '
                                                                    'OF'},
                                 'DRBs-ToBeSetup-List': {'element': {'actual-parameters': ['{'],
                                                                     'type': 'ProtocolIE-SingleContainer'},
                                                         'size': [(1,
                                                                   'maxnoofDRBs')],
                                                         'type': 'SEQUENCE OF'},
                                 'DRBs-ToBeSetupMod-List': {'element': {'actual-parameters': ['{'],
                                                                        'type': 'ProtocolIE-SingleContainer'},
                                                            'size': [(1,
                                                                      'maxnoofDRBs')],
                                                            'type': 'SEQUENCE '
                                                                    'OF'},
                                 'ErrorIndication': {'members': [{'actual-parameters': ['{'],
                                                                  'name': 'protocolIEs',
                                                                  'type': 'ProtocolIE-Container'},
                                                                 None],
                                                     'type': 'SEQUENCE'},
                                 'F1SetupFailure': {'members': [{'actual-parameters': ['{'],
                                                                 'name': 'protocolIEs',
                                                                 'type': 'ProtocolIE-Container'},
                                                                None],
                                                    'type': 'SEQUENCE'},
                                 'F1SetupRequest': {'members': [{'actual-parameters': ['{'],
                                                                 'name': 'protocolIEs',
                                                                 'type': 'ProtocolIE-Container'},
                                                                None],
                                                    'type': 'SEQUENCE'},
                                 'F1SetupResponse': {'members': [{'actual-parameters': ['{'],
                                                                  'name': 'protocolIEs',
                                                                  'type': 'ProtocolIE-Container'},
                                                                 None],
                                                     'type': 'SEQUENCE'},
                                 'GNB-CU-TNL-Association-Failed-To-Setup-List': {'element': {'actual-parameters': ['{'],
                                                                                             'type': 'ProtocolIE-SingleContainer'},
                                                                                 'size': [(1,
                                                                                           'maxnoofTNLAssociations')],
                                                                                 'type': 'SEQUENCE '
                                                                                         'OF'},
                                 'GNB-CU-TNL-Association-Setup-List': {'element': {'actual-parameters': ['{'],
                                                                                   'type': 'ProtocolIE-SingleContainer'},
                                                                       'size': [(1,
                                                                                 'maxnoofTNLAssociations')],
                                                                       'type': 'SEQUENCE '
                                                                               'OF'},
                                 'GNB-CU-TNL-Association-To-Add-List': {'element': {'actual-parameters': ['{'],
                                                                                    'type': 'ProtocolIE-SingleContainer'},
                                                                        'size': [(1,
                                                                                  'maxnoofTNLAssociations')],
                                                                        'type': 'SEQUENCE '
                                                                                'OF'},
                                 'GNB-CU-TNL-Association-To-Remove-List': {'element': {'actual-parameters': ['{'],
                                                                                       'type': 'ProtocolIE-SingleContainer'},
                                                                           'size': [(1,
                                                                                     'maxnoofTNLAssociations')],
                                                                           'type': 'SEQUENCE '
                                                                                   'OF'},
                                 'GNB-CU-TNL-Association-To-Update-List': {'element': {'actual-parameters': ['{'],
                                                                                       'type': 'ProtocolIE-SingleContainer'},
                                                                           'size': [(1,
                                                                                     'maxnoofTNLAssociations')],
                                                                           'type': 'SEQUENCE '
                                                                                   'OF'},
                                 'GNB-DU-Served-Cells-List': {'element': {'actual-parameters': ['{'],
                                                                          'type': 'ProtocolIE-SingleContainer'},
                                                              'size': [(1,
                                                                        'maxCellingNBDU')],
                                                              'type': 'SEQUENCE '
                                                                      'OF'},
                                 'GNBCUConfigurationUpdate': {'members': [{'actual-parameters': ['{'],
                                                                           'name': 'protocolIEs',
                                                                           'type': 'ProtocolIE-Container'},
                                                                          None],
                                                              'type': 'SEQUENCE'},
                                 'GNBCUConfigurationUpdateAcknowledge': {'members': [{'actual-parameters': ['{'],
                                                                                      'name': 'protocolIEs',
                                                                                      'type': 'ProtocolIE-Container'},
                                                                                     None],
                                                                         'type': 'SEQUENCE'},
                                 'GNBCUConfigurationUpdateFailure': {'members': [{'actual-parameters': ['{'],
                                                                                  'name': 'protocolIEs',
                                                                                  'type': 'ProtocolIE-Container'},
                                                                                 None],
                                                                     'type': 'SEQUENCE'},
                                 'GNBDUConfigurationUpdate': {'members': [{'actual-parameters': ['{'],
                                                                           'name': 'protocolIEs',
                                                                           'type': 'ProtocolIE-Container'},
                                                                          None],
                                                              'type': 'SEQUENCE'},
                                 'GNBDUConfigurationUpdateAcknowledge': {'members': [{'actual-parameters': ['{'],
                                                                                      'name': 'protocolIEs',
                                                                                      'type': 'ProtocolIE-Container'},
                                                                                     None],
                                                                         'type': 'SEQUENCE'},
                                 'GNBDUConfigurationUpdateFailure': {'members': [{'actual-parameters': ['{'],
                                                                                  'name': 'protocolIEs',
                                                                                  'type': 'ProtocolIE-Container'},
                                                                                 None],
                                                                     'type': 'SEQUENCE'},
                                 'GNBDUResourceCoordinationRequest': {'members': [{'actual-parameters': ['{'],
                                                                                   'name': 'protocolIEs',
                                                                                   'type': 'ProtocolIE-Container'},
                                                                                  None],
                                                                      'type': 'SEQUENCE'},
                                 'GNBDUResourceCoordinationResponse': {'members': [{'actual-parameters': ['{'],
                                                                                    'name': 'protocolIEs',
                                                                                    'type': 'ProtocolIE-Container'},
                                                                                   None],
                                                                       'type': 'SEQUENCE'},
                                 'GNBDUStatusIndication': {'members': [{'actual-parameters': ['{'],
                                                                        'name': 'protocolIEs',
                                                                        'type': 'ProtocolIE-Container'},
                                                                       None],
                                                           'type': 'SEQUENCE'},
                                 'InitialULRRCMessageTransfer': {'members': [{'actual-parameters': ['{'],
                                                                              'name': 'protocolIEs',
                                                                              'type': 'ProtocolIE-Container'},
                                                                             None],
                                                                 'type': 'SEQUENCE'},
                                 'NR-CGI-List-For-Restart-List': {'element': {'actual-parameters': ['{'],
                                                                              'type': 'ProtocolIE-SingleContainer'},
                                                                  'size': [(1,
                                                                            'maxCellingNBDU')],
                                                                  'type': 'SEQUENCE '
                                                                          'OF'},
                                 'Notify': {'members': [{'actual-parameters': ['{'],
                                                         'name': 'protocolIEs',
                                                         'type': 'ProtocolIE-Container'},
                                                        None],
                                            'type': 'SEQUENCE'},
                                 'PWS-Failed-NR-CGI-List': {'element': {'actual-parameters': ['{'],
                                                                        'type': 'ProtocolIE-SingleContainer'},
                                                            'size': [(1,
                                                                      'maxCellingNBDU')],
                                                            'type': 'SEQUENCE '
                                                                    'OF'},
                                 'PWSCancelRequest': {'members': [{'actual-parameters': ['{'],
                                                                   'name': 'protocolIEs',
                                                                   'type': 'ProtocolIE-Container'},
                                                                  None],
                                                      'type': 'SEQUENCE'},
                                 'PWSCancelResponse': {'members': [{'actual-parameters': ['{'],
                                                                    'name': 'protocolIEs',
                                                                    'type': 'ProtocolIE-Container'},
                                                                   None],
                                                       'type': 'SEQUENCE'},
                                 'PWSFailureIndication': {'members': [{'actual-parameters': ['{'],
                                                                       'name': 'protocolIEs',
                                                                       'type': 'ProtocolIE-Container'},
                                                                      None],
                                                          'type': 'SEQUENCE'},
                                 'PWSRestartIndication': {'members': [{'actual-parameters': ['{'],
                                                                       'name': 'protocolIEs',
                                                                       'type': 'ProtocolIE-Container'},
                                                                      None],
                                                          'type': 'SEQUENCE'},
                                 'Paging': {'members': [{'actual-parameters': ['{'],
                                                         'name': 'protocolIEs',
                                                         'type': 'ProtocolIE-Container'},
                                                        None],
                                            'type': 'SEQUENCE'},
                                 'PagingCell-list': {'element': {'actual-parameters': ['{'],
                                                                 'type': 'ProtocolIE-SingleContainer'},
                                                     'size': [(1,
                                                               'maxnoofPagingCells')],
                                                     'type': 'SEQUENCE OF'},
                                 'Potential-SpCell-List': {'element': {'actual-parameters': ['{'],
                                                                       'type': 'ProtocolIE-SingleContainer'},
                                                           'size': [(0,
                                                                     'maxnoofPotentialSpCells')],
                                                           'type': 'SEQUENCE '
                                                                   'OF'},
                                 'PrivateMessage': {'members': [{'actual-parameters': ['{'],
                                                                 'name': 'privateIEs',
                                                                 'type': 'PrivateIE-Container'},
                                                                None],
                                                    'type': 'SEQUENCE'},
                                 'Protected-EUTRA-Resources-List': {'element': {'actual-parameters': ['{'],
                                                                                'type': 'ProtocolIE-SingleContainer'},
                                                                    'size': [(1,
                                                                              'maxCellineNB')],
                                                                    'type': 'SEQUENCE '
                                                                            'OF'},
                                 'Reset': {'members': [{'actual-parameters': ['{'],
                                                        'name': 'protocolIEs',
                                                        'type': 'ProtocolIE-Container'},
                                                       None],
                                           'type': 'SEQUENCE'},
                                 'ResetAcknowledge': {'members': [{'actual-parameters': ['{'],
                                                                   'name': 'protocolIEs',
                                                                   'type': 'ProtocolIE-Container'},
                                                                  None],
                                                      'type': 'SEQUENCE'},
                                 'ResetAll': {'type': 'ENUMERATED',
                                              'values': [('reset-all', 0),
                                                         None]},
                                 'ResetType': {'members': [{'name': 'f1-Interface',
                                                            'type': 'ResetAll'},
                                                           {'name': 'partOfF1-Interface',
                                                            'type': 'UE-associatedLogicalF1-ConnectionListRes'},
                                                           {'actual-parameters': ['{'],
                                                            'name': 'choice-extension',
                                                            'type': 'ProtocolIE-SingleContainer'}],
                                               'type': 'CHOICE'},
                                 'SCell-FailedtoSetup-List': {'element': {'actual-parameters': ['{'],
                                                                          'type': 'ProtocolIE-SingleContainer'},
                                                              'size': [(1,
                                                                        'maxnoofSCells')],
                                                              'type': 'SEQUENCE '
                                                                      'OF'},
                                 'SCell-FailedtoSetupMod-List': {'element': {'actual-parameters': ['{'],
                                                                             'type': 'ProtocolIE-SingleContainer'},
                                                                 'size': [(1,
                                                                           'maxnoofSCells')],
                                                                 'type': 'SEQUENCE '
                                                                         'OF'},
                                 'SCell-ToBeRemoved-List': {'element': {'actual-parameters': ['{'],
                                                                        'type': 'ProtocolIE-SingleContainer'},
                                                            'size': [(1,
                                                                      'maxnoofSCells')],
                                                            'type': 'SEQUENCE '
                                                                    'OF'},
                                 'SCell-ToBeSetup-List': {'element': {'actual-parameters': ['{'],
                                                                      'type': 'ProtocolIE-SingleContainer'},
                                                          'size': [(1,
                                                                    'maxnoofSCells')],
                                                          'type': 'SEQUENCE '
                                                                  'OF'},
                                 'SCell-ToBeSetupMod-List': {'element': {'actual-parameters': ['{'],
                                                                         'type': 'ProtocolIE-SingleContainer'},
                                                             'size': [(1,
                                                                       'maxnoofSCells')],
                                                             'type': 'SEQUENCE '
                                                                     'OF'},
                                 'SRBs-FailedToBeSetup-List': {'element': {'actual-parameters': ['{'],
                                                                           'type': 'ProtocolIE-SingleContainer'},
                                                               'size': [(1,
                                                                         'maxnoofSRBs')],
                                                               'type': 'SEQUENCE '
                                                                       'OF'},
                                 'SRBs-FailedToBeSetupMod-List': {'element': {'actual-parameters': ['{'],
                                                                              'type': 'ProtocolIE-SingleContainer'},
                                                                  'size': [(1,
                                                                            'maxnoofSRBs')],
                                                                  'type': 'SEQUENCE '
                                                                          'OF'},
                                 'SRBs-Required-ToBeReleased-List': {'element': {'actual-parameters': ['{'],
                                                                                 'type': 'ProtocolIE-SingleContainer'},
                                                                     'size': [(1,
                                                                               'maxnoofSRBs')],
                                                                     'type': 'SEQUENCE '
                                                                             'OF'},
                                 'SRBs-ToBeReleased-List': {'element': {'actual-parameters': ['{'],
                                                                        'type': 'ProtocolIE-SingleContainer'},
                                                            'size': [(1,
                                                                      'maxnoofSRBs')],
                                                            'type': 'SEQUENCE '
                                                                    'OF'},
                                 'SRBs-ToBeSetup-List': {'element': {'actual-parameters': ['{'],
                                                                     'type': 'ProtocolIE-SingleContainer'},
                                                         'size': [(1,
                                                                   'maxnoofSRBs')],
                                                         'type': 'SEQUENCE OF'},
                                 'SRBs-ToBeSetupMod-List': {'element': {'actual-parameters': ['{'],
                                                                        'type': 'ProtocolIE-SingleContainer'},
                                                            'size': [(1,
                                                                      'maxnoofSRBs')],
                                                            'type': 'SEQUENCE '
                                                                    'OF'},
                                 'Served-Cells-To-Add-List': {'element': {'actual-parameters': ['{'],
                                                                          'type': 'ProtocolIE-SingleContainer'},
                                                              'size': [(1,
                                                                        'maxCellingNBDU')],
                                                              'type': 'SEQUENCE '
                                                                      'OF'},
                                 'Served-Cells-To-Delete-List': {'element': {'actual-parameters': ['{'],
                                                                             'type': 'ProtocolIE-SingleContainer'},
                                                                 'size': [(1,
                                                                           'maxCellingNBDU')],
                                                                 'type': 'SEQUENCE '
                                                                         'OF'},
                                 'Served-Cells-To-Modify-List': {'element': {'actual-parameters': ['{'],
                                                                             'type': 'ProtocolIE-SingleContainer'},
                                                                 'size': [(1,
                                                                           'maxCellingNBDU')],
                                                                 'type': 'SEQUENCE '
                                                                         'OF'},
                                 'SystemInformationDeliveryCommand': {'members': [{'actual-parameters': ['{'],
                                                                                   'name': 'protocolIEs',
                                                                                   'type': 'ProtocolIE-Container'},
                                                                                  None],
                                                                      'type': 'SEQUENCE'},
                                 'UE-associatedLogicalF1-ConnectionListRes': {'element': {'actual-parameters': ['{'],
                                                                                          'type': 'ProtocolIE-SingleContainer'},
                                                                              'size': [(1,
                                                                                        'maxnoofIndividualF1ConnectionsToReset')],
                                                                              'type': 'SEQUENCE '
                                                                                      'OF'},
                                 'UE-associatedLogicalF1-ConnectionListResAck': {'element': {'actual-parameters': ['{'],
                                                                                             'type': 'ProtocolIE-SingleContainer'},
                                                                                 'size': [(1,
                                                                                           'maxnoofIndividualF1ConnectionsToReset')],
                                                                                 'type': 'SEQUENCE '
                                                                                         'OF'},
                                 'UEContextModificationConfirm': {'members': [{'actual-parameters': ['{'],
                                                                               'name': 'protocolIEs',
                                                                               'type': 'ProtocolIE-Container'},
                                                                              None],
                                                                  'type': 'SEQUENCE'},
                                 'UEContextModificationFailure': {'members': [{'actual-parameters': ['{'],
                                                                               'name': 'protocolIEs',
                                                                               'type': 'ProtocolIE-Container'},
                                                                              None],
                                                                  'type': 'SEQUENCE'},
                                 'UEContextModificationRequest': {'members': [{'actual-parameters': ['{'],
                                                                               'name': 'protocolIEs',
                                                                               'type': 'ProtocolIE-Container'},
                                                                              None],
                                                                  'type': 'SEQUENCE'},
                                 'UEContextModificationRequired': {'members': [{'actual-parameters': ['{'],
                                                                                'name': 'protocolIEs',
                                                                                'type': 'ProtocolIE-Container'},
                                                                               None],
                                                                   'type': 'SEQUENCE'},
                                 'UEContextModificationResponse': {'members': [{'actual-parameters': ['{'],
                                                                                'name': 'protocolIEs',
                                                                                'type': 'ProtocolIE-Container'},
                                                                               None],
                                                                   'type': 'SEQUENCE'},
                                 'UEContextReleaseCommand': {'members': [{'actual-parameters': ['{'],
                                                                          'name': 'protocolIEs',
                                                                          'type': 'ProtocolIE-Container'},
                                                                         None],
                                                             'type': 'SEQUENCE'},
                                 'UEContextReleaseComplete': {'members': [{'actual-parameters': ['{'],
                                                                           'name': 'protocolIEs',
                                                                           'type': 'ProtocolIE-Container'},
                                                                          None],
                                                              'type': 'SEQUENCE'},
                                 'UEContextReleaseRequest': {'members': [{'actual-parameters': ['{'],
                                                                          'name': 'protocolIEs',
                                                                          'type': 'ProtocolIE-Container'},
                                                                         None],
                                                             'type': 'SEQUENCE'},
                                 'UEContextSetupFailure': {'members': [{'actual-parameters': ['{'],
                                                                        'name': 'protocolIEs',
                                                                        'type': 'ProtocolIE-Container'},
                                                                       None],
                                                           'type': 'SEQUENCE'},
                                 'UEContextSetupRequest': {'members': [{'actual-parameters': ['{'],
                                                                        'name': 'protocolIEs',
                                                                        'type': 'ProtocolIE-Container'},
                                                                       None],
                                                           'type': 'SEQUENCE'},
                                 'UEContextSetupResponse': {'members': [{'actual-parameters': ['{'],
                                                                         'name': 'protocolIEs',
                                                                         'type': 'ProtocolIE-Container'},
                                                                        None],
                                                            'type': 'SEQUENCE'},
                                 'UEInactivityNotification': {'members': [{'actual-parameters': ['{'],
                                                                           'name': 'protocolIEs',
                                                                           'type': 'ProtocolIE-Container'},
                                                                          None],
                                                              'type': 'SEQUENCE'},
                                 'ULRRCMessageTransfer': {'members': [{'actual-parameters': ['{'],
                                                                       'name': 'protocolIEs',
                                                                       'type': 'ProtocolIE-Container'},
                                                                      None],
                                                          'type': 'SEQUENCE'},
                                 'WriteReplaceWarningRequest': {'members': [{'actual-parameters': ['{'],
                                                                             'name': 'protocolIEs',
                                                                             'type': 'ProtocolIE-Container'},
                                                                            None],
                                                                'type': 'SEQUENCE'},
                                 'WriteReplaceWarningResponse': {'members': [{'actual-parameters': ['{'],
                                                                              'name': 'protocolIEs',
                                                                              'type': 'ProtocolIE-Container'},
                                                                             None],
                                                                 'type': 'SEQUENCE'}},
                       'values': {}}}