EXPECTED = {'F1AP-Constants': {'extensibility-implied': False,
                    'imports': {'F1AP-CommonDataTypes': ['ProcedureCode',
                                                         'ProtocolIE-ID']},
                    'object-classes': {},
                    'object-sets': {},
                    'tags': 'AUTOMATIC',
                    'types': {},
                    'values': {'id-AvailablePLMNList': {'type': 'ProtocolIE-ID',
                                                        'value': 179},
                               'id-Broadcast-To-Be-Cancelled-Item': {'type': 'ProtocolIE-ID',
                                                                     'value': 149},
                               'id-Broadcast-To-Be-Cancelled-List': {'type': 'ProtocolIE-ID',
                                                                     'value': 148},
                               'id-C-RNTI': {'type': 'ProtocolIE-ID',
                                             'value': 95},
                               'id-CUtoDURRCInformation': {'type': 'ProtocolIE-ID',
                                                           'value': 9},
                               'id-Cancel-all-Warning-Messages-Indicator': {'type': 'ProtocolIE-ID',
                                                                            'value': 157},
                               'id-Candidate-SpCell-Item': {'type': 'ProtocolIE-ID',
                                                            'value': 91},
                               'id-Candidate-SpCell-List': {'type': 'ProtocolIE-ID',
                                                            'value': 90},
                               'id-Cause': {'type': 'ProtocolIE-ID',
                                            'value': 0},
                               'id-CellGroupConfig': {'type': 'ProtocolIE-ID',
                                                      'value': 173},
                               'id-Cells-Broadcast-Cancelled-Item': {'type': 'ProtocolIE-ID',
                                                                     'value': 151},
                               'id-Cells-Broadcast-Cancelled-List': {'type': 'ProtocolIE-ID',
                                                                     'value': 150},
                               'id-Cells-Broadcast-Completed-Item': {'type': 'ProtocolIE-ID',
                                                                     'value': 147},
                               'id-Cells-Broadcast-Completed-List': {'type': 'ProtocolIE-ID',
                                                                     'value': 146},
                               'id-Cells-Failed-to-be-Activated-List': {'type': 'ProtocolIE-ID',
                                                                        'value': 1},
                               'id-Cells-Failed-to-be-Activated-List-Item': {'type': 'ProtocolIE-ID',
                                                                             'value': 2},
                               'id-Cells-Status-Item': {'type': 'ProtocolIE-ID',
                                                        'value': 88},
                               'id-Cells-Status-List': {'type': 'ProtocolIE-ID',
                                                        'value': 89},
                               'id-Cells-To-Be-Broadcast-Item': {'type': 'ProtocolIE-ID',
                                                                 'value': 145},
                               'id-Cells-To-Be-Broadcast-List': {'type': 'ProtocolIE-ID',
                                                                 'value': 144},
                               'id-Cells-to-be-Activated-List': {'type': 'ProtocolIE-ID',
                                                                 'value': 3},
                               'id-Cells-to-be-Activated-List-Item': {'type': 'ProtocolIE-ID',
                                                                      'value': 4},
                               'id-Cells-to-be-Barred-Item': {'type': 'ProtocolIE-ID',
                                                              'value': 130},
                               'id-Cells-to-be-Barred-List': {'type': 'ProtocolIE-ID',
                                                              'value': 129},
                               'id-Cells-to-be-Deactivated-List': {'type': 'ProtocolIE-ID',
                                                                   'value': 5},
                               'id-Cells-to-be-Deactivated-List-Item': {'type': 'ProtocolIE-ID',
                                                                        'value': 6},
                               'id-ConfirmedUEID': {'type': 'ProtocolIE-ID',
                                                    'value': 156},
                               'id-CriticalityDiagnostics': {'type': 'ProtocolIE-ID',
                                                             'value': 7},
                               'id-DC-Based-Duplication-Activation': {'type': 'ProtocolIE-ID',
                                                                      'value': 177},
                               'id-DC-Based-Duplication-Configured': {'type': 'ProtocolIE-ID',
                                                                      'value': 176},
                               'id-DLRRCMessageTransfer': {'type': 'ProcedureCode',
                                                           'value': 12},
                               'id-DRB-Activity-Item': {'type': 'ProtocolIE-ID',
                                                        'value': 99},
                               'id-DRB-Activity-List': {'type': 'ProtocolIE-ID',
                                                        'value': 100},
                               'id-DRB-Information': {'type': 'ProtocolIE-ID',
                                                      'value': 164},
                               'id-DRB-Notify-Item': {'type': 'ProtocolIE-ID',
                                                      'value': 136},
                               'id-DRB-Notify-List': {'type': 'ProtocolIE-ID',
                                                      'value': 137},
                               'id-DRBs-FailedToBeModified-Item': {'type': 'ProtocolIE-ID',
                                                                   'value': 12},
                               'id-DRBs-FailedToBeModified-List': {'type': 'ProtocolIE-ID',
                                                                   'value': 13},
                               'id-DRBs-FailedToBeSetup-Item': {'type': 'ProtocolIE-ID',
                                                                'value': 14},
                               'id-DRBs-FailedToBeSetup-List': {'type': 'ProtocolIE-ID',
                                                                'value': 15},
                               'id-DRBs-FailedToBeSetupMod-Item': {'type': 'ProtocolIE-ID',
                                                                   'value': 16},
                               'id-DRBs-FailedToBeSetupMod-List': {'type': 'ProtocolIE-ID',
                                                                   'value': 17},
                               'id-DRBs-Modified-Item': {'type': 'ProtocolIE-ID',
                                                         'value': 20},
                               'id-DRBs-Modified-List': {'type': 'ProtocolIE-ID',
                                                         'value': 21},
                               'id-DRBs-ModifiedConf-Item': {'type': 'ProtocolIE-ID',
                                                             'value': 18},
                               'id-DRBs-ModifiedConf-List': {'type': 'ProtocolIE-ID',
                                                             'value': 19},
                               'id-DRBs-Required-ToBeModified-Item': {'type': 'ProtocolIE-ID',
                                                                      'value': 22},
                               'id-DRBs-Required-ToBeModified-List': {'type': 'ProtocolIE-ID',
                                                                      'value': 23},
                               'id-DRBs-Required-ToBeReleased-Item': {'type': 'ProtocolIE-ID',
                                                                      'value': 24},
                               'id-DRBs-Required-ToBeReleased-List': {'type': 'ProtocolIE-ID',
                                                                      'value': 25},
                               'id-DRBs-Setup-Item': {'type': 'ProtocolIE-ID',
                                                      'value': 26},
                               'id-DRBs-Setup-List': {'type': 'ProtocolIE-ID',
                                                      'value': 27},
                               'id-DRBs-SetupMod-Item': {'type': 'ProtocolIE-ID',
                                                         'value': 28},
                               'id-DRBs-SetupMod-List': {'type': 'ProtocolIE-ID',
                                                         'value': 29},
                               'id-DRBs-ToBeModified-Item': {'type': 'ProtocolIE-ID',
                                                             'value': 30},
                               'id-DRBs-ToBeModified-List': {'type': 'ProtocolIE-ID',
                                                             'value': 31},
                               'id-DRBs-ToBeReleased-Item': {'type': 'ProtocolIE-ID',
                                                             'value': 32},
                               'id-DRBs-ToBeReleased-List': {'type': 'ProtocolIE-ID',
                                                             'value': 33},
                               'id-DRBs-ToBeSetup-Item': {'type': 'ProtocolIE-ID',
                                                          'value': 34},
                               'id-DRBs-ToBeSetup-List': {'type': 'ProtocolIE-ID',
                                                          'value': 35},
                               'id-DRBs-ToBeSetupMod-Item': {'type': 'ProtocolIE-ID',
                                                             'value': 36},
                               'id-DRBs-ToBeSetupMod-List': {'type': 'ProtocolIE-ID',
                                                             'value': 37},
                               'id-DRXConfigurationIndicator': {'type': 'ProtocolIE-ID',
                                                                'value': 159},
                               'id-DRXCycle': {'type': 'ProtocolIE-ID',
                                               'value': 38},
                               'id-DUtoCURRCContainer': {'type': 'ProtocolIE-ID',
                                                         'value': 128},
                               'id-DUtoCURRCInformation': {'type': 'ProtocolIE-ID',
                                                           'value': 39},
                               'id-EUTRA-NR-CellResourceCoordinationReq-Container': {'type': 'ProtocolIE-ID',
                                                                                     'value': 101},
                               'id-EUTRA-NR-CellResourceCoordinationReqAck-Container': {'type': 'ProtocolIE-ID',
                                                                                        'value': 102},
                               'id-ErrorIndication': {'type': 'ProcedureCode',
                                                      'value': 2},
                               'id-ExecuteDuplication': {'type': 'ProtocolIE-ID',
                                                         'value': 109},
                               'id-F1Setup': {'type': 'ProcedureCode',
                                              'value': 1},
                               'id-FullConfiguration': {'type': 'ProtocolIE-ID',
                                                        'value': 94},
                               'id-GNB-CU-RRC-Version': {'type': 'ProtocolIE-ID',
                                                         'value': 170},
                               'id-GNB-CU-TNL-Association-Failed-To-Setup-Item': {'type': 'ProtocolIE-ID',
                                                                                  'value': 135},
                               'id-GNB-CU-TNL-Association-Failed-To-Setup-List': {'type': 'ProtocolIE-ID',
                                                                                  'value': 134},
                               'id-GNB-CU-TNL-Association-Setup-Item': {'type': 'ProtocolIE-ID',
                                                                        'value': 133},
                               'id-GNB-CU-TNL-Association-Setup-List': {'type': 'ProtocolIE-ID',
                                                                        'value': 132},
                               'id-GNB-CU-TNL-Association-To-Add-Item': {'type': 'ProtocolIE-ID',
                                                                         'value': 120},
                               'id-GNB-CU-TNL-Association-To-Add-List': {'type': 'ProtocolIE-ID',
                                                                         'value': 121},
                               'id-GNB-CU-TNL-Association-To-Remove-Item': {'type': 'ProtocolIE-ID',
                                                                            'value': 122},
                               'id-GNB-CU-TNL-Association-To-Remove-List': {'type': 'ProtocolIE-ID',
                                                                            'value': 123},
                               'id-GNB-CU-TNL-Association-To-Update-Item': {'type': 'ProtocolIE-ID',
                                                                            'value': 124},
                               'id-GNB-CU-TNL-Association-To-Update-List': {'type': 'ProtocolIE-ID',
                                                                            'value': 125},
                               'id-GNB-DU-RRC-Version': {'type': 'ProtocolIE-ID',
                                                         'value': 171},
                               'id-GNB-DU-Served-Cells-Item': {'type': 'ProtocolIE-ID',
                                                               'value': 43},
                               'id-GNB-DU-UE-AMBR-UL': {'type': 'ProtocolIE-ID',
                                                        'value': 158},
                               'id-GNB-DUConfigurationQuery': {'type': 'ProtocolIE-ID',
                                                               'value': 162},
                               'id-GNBDUOverloadInformation': {'type': 'ProtocolIE-ID',
                                                               'value': 172},
                               'id-GNBDUResourceCoordination': {'type': 'ProcedureCode',
                                                                'value': 16},
                               'id-GNBDUStatusIndication': {'type': 'ProcedureCode',
                                                            'value': 24},
                               'id-HandoverPreparationInformation': {'type': 'ProtocolIE-ID',
                                                                     'value': 119},
                               'id-InactivityMonitoringRequest': {'type': 'ProtocolIE-ID',
                                                                  'value': 97},
                               'id-InactivityMonitoringResponse': {'type': 'ProtocolIE-ID',
                                                                   'value': 98},
                               'id-InitialULRRCMessageTransfer': {'type': 'ProcedureCode',
                                                                  'value': 11},
                               'id-MaskedIMEISV': {'type': 'ProtocolIE-ID',
                                                   'value': 126},
                               'id-MeasurementTimingConfiguration': {'type': 'ProtocolIE-ID',
                                                                     'value': 163},
                               'id-NR-CGI-List-For-Restart-Item': {'type': 'ProtocolIE-ID',
                                                                   'value': 153},
                               'id-NR-CGI-List-For-Restart-List': {'type': 'ProtocolIE-ID',
                                                                   'value': 152},
                               'id-NRCGI': {'type': 'ProtocolIE-ID',
                                            'value': 111},
                               'id-NRCellID': {'type': 'ProtocolIE-ID',
                                               'value': 46},
                               'id-NotficationControl': {'type': 'ProtocolIE-ID',
                                                         'value': 138},
                               'id-Notify': {'type': 'ProcedureCode',
                                             'value': 19},
                               'id-NumberofBroadcastRequest': {'type': 'ProtocolIE-ID',
                                                               'value': 142},
                               'id-PDCPSNLength': {'type': 'ProtocolIE-ID',
                                                   'value': 161},
                               'id-PDUSessionID': {'type': 'ProtocolIE-ID',
                                                   'value': 180},
                               'id-PWS-Failed-NR-CGI-Item': {'type': 'ProtocolIE-ID',
                                                             'value': 155},
                               'id-PWS-Failed-NR-CGI-List': {'type': 'ProtocolIE-ID',
                                                             'value': 154},
                               'id-PWSCancel': {'type': 'ProcedureCode',
                                                'value': 21},
                               'id-PWSFailureIndication': {'type': 'ProcedureCode',
                                                           'value': 23},
                               'id-PWSRestartIndication': {'type': 'ProcedureCode',
                                                           'value': 22},
                               'id-PWSSystemInformation': {'type': 'ProtocolIE-ID',
                                                           'value': 140},
                               'id-Paging': {'type': 'ProcedureCode',
                                             'value': 18},
                               'id-PagingCell-Item': {'type': 'ProtocolIE-ID',
                                                      'value': 112},
                               'id-PagingCell-List': {'type': 'ProtocolIE-ID',
                                                      'value': 113},
                               'id-PagingDRX': {'type': 'ProtocolIE-ID',
                                                'value': 114},
                               'id-PagingIdentity': {'type': 'ProtocolIE-ID',
                                                     'value': 127},
                               'id-PagingPriority': {'type': 'ProtocolIE-ID',
                                                     'value': 115},
                               'id-Potential-SpCell-Item': {'type': 'ProtocolIE-ID',
                                                            'value': 93},
                               'id-Potential-SpCell-List': {'type': 'ProtocolIE-ID',
                                                            'value': 92},
                               'id-Protected-EUTRA-Resources-Item': {'type': 'ProtocolIE-ID',
                                                                     'value': 168},
                               'id-Protected-EUTRA-Resources-List': {'type': 'ProtocolIE-ID',
                                                                     'value': 105},
                               'id-RANAC': {'type': 'ProtocolIE-ID',
                                            'value': 139},
                               'id-RAT-FrequencyPriorityInformation': {'type': 'ProtocolIE-ID',
                                                                       'value': 108},
                               'id-RLC-Status': {'type': 'ProtocolIE-ID',
                                                 'value': 160},
                               'id-RLCFailureIndication': {'type': 'ProtocolIE-ID',
                                                           'value': 174},
                               'id-RRCContainer': {'type': 'ProtocolIE-ID',
                                                   'value': 50},
                               'id-RRCRconfigurationCompleteIndicator': {'type': 'ProtocolIE-ID',
                                                                         'value': 87},
                               'id-RepetitionPeriod': {'type': 'ProtocolIE-ID',
                                                       'value': 141},
                               'id-RequestType': {'type': 'ProtocolIE-ID',
                                                  'value': 106},
                               'id-Reset': {'type': 'ProcedureCode',
                                            'value': 0},
                               'id-ResetType': {'type': 'ProtocolIE-ID',
                                                'value': 48},
                               'id-ResourceCoordinationTransferContainer': {'type': 'ProtocolIE-ID',
                                                                            'value': 49},
                               'id-SCell-FailedtoSetup-Item': {'type': 'ProtocolIE-ID',
                                                               'value': 84},
                               'id-SCell-FailedtoSetup-List': {'type': 'ProtocolIE-ID',
                                                               'value': 83},
                               'id-SCell-FailedtoSetupMod-Item': {'type': 'ProtocolIE-ID',
                                                                  'value': 86},
                               'id-SCell-FailedtoSetupMod-List': {'type': 'ProtocolIE-ID',
                                                                  'value': 85},
                               'id-SCell-ToBeRemoved-Item': {'type': 'ProtocolIE-ID',
                                                             'value': 51},
                               'id-SCell-ToBeRemoved-List': {'type': 'ProtocolIE-ID',
                                                             'value': 52},
                               'id-SCell-ToBeSetup-Item': {'type': 'ProtocolIE-ID',
                                                           'value': 53},
                               'id-SCell-ToBeSetup-List': {'type': 'ProtocolIE-ID',
                                                           'value': 54},
                               'id-SCell-ToBeSetupMod-Item': {'type': 'ProtocolIE-ID',
                                                              'value': 55},
                               'id-SCell-ToBeSetupMod-List': {'type': 'ProtocolIE-ID',
                                                              'value': 56},
                               'id-SItype-List': {'type': 'ProtocolIE-ID',
                                                  'value': 116},
                               'id-SRBID': {'type': 'ProtocolIE-ID',
                                            'value': 64},
                               'id-SRBs-FailedToBeSetup-Item': {'type': 'ProtocolIE-ID',
                                                                'value': 65},
                               'id-SRBs-FailedToBeSetup-List': {'type': 'ProtocolIE-ID',
                                                                'value': 66},
                               'id-SRBs-FailedToBeSetupMod-Item': {'type': 'ProtocolIE-ID',
                                                                   'value': 67},
                               'id-SRBs-FailedToBeSetupMod-List': {'type': 'ProtocolIE-ID',
                                                                   'value': 68},
                               'id-SRBs-Required-ToBeReleased-Item': {'type': 'ProtocolIE-ID',
                                                                      'value': 69},
                               'id-SRBs-Required-ToBeReleased-List': {'type': 'ProtocolIE-ID',
                                                                      'value': 70},
                               'id-SRBs-ToBeReleased-Item': {'type': 'ProtocolIE-ID',
                                                             'value': 71},
                               'id-SRBs-ToBeReleased-List': {'type': 'ProtocolIE-ID',
                                                             'value': 72},
                               'id-SRBs-ToBeSetup-Item': {'type': 'ProtocolIE-ID',
                                                          'value': 73},
                               'id-SRBs-ToBeSetup-List': {'type': 'ProtocolIE-ID',
                                                          'value': 74},
                               'id-SRBs-ToBeSetupMod-Item': {'type': 'ProtocolIE-ID',
                                                             'value': 75},
                               'id-SRBs-ToBeSetupMod-List': {'type': 'ProtocolIE-ID',
                                                             'value': 76},
                               'id-SULAccessIndication': {'type': 'ProtocolIE-ID',
                                                          'value': 178},
                               'id-ServCellndex': {'type': 'ProtocolIE-ID',
                                                   'value': 107},
                               'id-Served-Cells-To-Add-Item': {'type': 'ProtocolIE-ID',
                                                               'value': 57},
                               'id-Served-Cells-To-Add-List': {'type': 'ProtocolIE-ID',
                                                               'value': 58},
                               'id-Served-Cells-To-Delete-Item': {'type': 'ProtocolIE-ID',
                                                                  'value': 59},
                               'id-Served-Cells-To-Delete-List': {'type': 'ProtocolIE-ID',
                                                                  'value': 60},
                               'id-Served-Cells-To-Modify-Item': {'type': 'ProtocolIE-ID',
                                                                  'value': 61},
                               'id-Served-Cells-To-Modify-List': {'type': 'ProtocolIE-ID',
                                                                  'value': 62},
                               'id-ServingPLMN': {'type': 'ProtocolIE-ID',
                                                  'value': 165},
                               'id-SpCell-ID': {'type': 'ProtocolIE-ID',
                                                'value': 63},
                               'id-SpCellULConfigured': {'type': 'ProtocolIE-ID',
                                                         'value': 96},
                               'id-SystemInformationDeliveryCommand': {'type': 'ProcedureCode',
                                                                       'value': 17},
                               'id-TAISliceSupportList': {'type': 'ProtocolIE-ID',
                                                          'value': 131},
                               'id-TimeToWait': {'type': 'ProtocolIE-ID',
                                                 'value': 77},
                               'id-TransactionID': {'type': 'ProtocolIE-ID',
                                                    'value': 78},
                               'id-TransmissionStopIndicator': {'type': 'ProtocolIE-ID',
                                                                'value': 79},
                               'id-UE-associatedLogicalF1-ConnectionItem': {'type': 'ProtocolIE-ID',
                                                                            'value': 80},
                               'id-UE-associatedLogicalF1-ConnectionListResAck': {'type': 'ProtocolIE-ID',
                                                                                  'value': 81},
                               'id-UEContextModification': {'type': 'ProcedureCode',
                                                            'value': 7},
                               'id-UEContextModificationRequired': {'type': 'ProcedureCode',
                                                                    'value': 8},
                               'id-UEContextRelease': {'type': 'ProcedureCode',
                                                       'value': 6},
                               'id-UEContextReleaseRequest': {'type': 'ProcedureCode',
                                                              'value': 10},
                               'id-UEContextSetup': {'type': 'ProcedureCode',
                                                     'value': 5},
                               'id-UEIdentityIndexValue': {'type': 'ProtocolIE-ID',
                                                           'value': 117},
                               'id-UEInactivityNotification': {'type': 'ProcedureCode',
                                                               'value': 15},
                               'id-UEMobilityCommand': {'type': 'ProcedureCode',
                                                        'value': 9},
                               'id-ULPDUSessionAggregateMaximumBitRate': {'type': 'ProtocolIE-ID',
                                                                          'value': 181},
                               'id-ULRRCMessageTransfer': {'type': 'ProcedureCode',
                                                           'value': 13},
                               'id-UplinkTxDirectCurrentListInformation': {'type': 'ProtocolIE-ID',
                                                                           'value': 175},
                               'id-WriteReplaceWarning': {'type': 'ProcedureCode',
                                                          'value': 20},
                               'id-gNB-CU-Name': {'type': 'ProtocolIE-ID',
                                                  'value': 82},
                               'id-gNB-CU-UE-F1AP-ID': {'type': 'ProtocolIE-ID',
                                                        'value': 40},
                               'id-gNB-CUSystemInformation': {'type': 'ProtocolIE-ID',
                                                              'value': 118},
                               'id-gNB-DU-ID': {'type': 'ProtocolIE-ID',
                                                'value': 42},
                               'id-gNB-DU-Name': {'type': 'ProtocolIE-ID',
                                                  'value': 45},
                               'id-gNB-DU-Served-Cells-List': {'type': 'ProtocolIE-ID',
                                                               'value': 44},
                               'id-gNB-DU-UE-F1AP-ID': {'type': 'ProtocolIE-ID',
                                                        'value': 41},
                               'id-gNBCUConfigurationUpdate': {'type': 'ProcedureCode',
                                                               'value': 4},
                               'id-gNBDUConfigurationUpdate': {'type': 'ProcedureCode',
                                                               'value': 3},
                               'id-oldgNB-DU-UE-F1AP-ID': {'type': 'ProtocolIE-ID',
                                                           'value': 47},
                               'id-privateMessage': {'type': 'ProcedureCode',
                                                     'value': 14},
                               'maxCellineNB': {'type': 'INTEGER',
                                                'value': 256},
                               'maxCellingNBDU': {'type': 'INTEGER',
                                                  'value': 512},
                               'maxNRARFCN': {'type': 'INTEGER',
                                              'value': 3279165},
                               'maxPrivateIEs': {'type': 'INTEGER',
                                                 'value': 65535},
                               'maxProtocolExtensions': {'type': 'INTEGER',
                                                         'value': 65535},
                               'maxProtocolIEs': {'type': 'INTEGER',
                                                  'value': 65535},
                               'maxnoofBPLMNs': {'type': 'INTEGER', 'value': 6},
                               'maxnoofCandidateSpCells': {'type': 'INTEGER',
                                                           'value': 64},
                               'maxnoofDLUPTNLInformation': {'type': 'INTEGER',
                                                             'value': 2},
                               'maxnoofDRBs': {'type': 'INTEGER', 'value': 64},
                               'maxnoofErrors': {'type': 'INTEGER',
                                                 'value': 256},
                               'maxnoofIndividualF1ConnectionsToReset': {'type': 'INTEGER',
                                                                         'value': 65536},
                               'maxnoofNrCellBands': {'type': 'INTEGER',
                                                      'value': 32},
                               'maxnoofPagingCells': {'type': 'INTEGER',
                                                      'value': 512},
                               'maxnoofPotentialSpCells': {'type': 'INTEGER',
                                                           'value': 64},
                               'maxnoofQoSFlows': {'type': 'INTEGER',
                                                   'value': 64},
                               'maxnoofSCells': {'type': 'INTEGER',
                                                 'value': 32},
                               'maxnoofSIBTypes': {'type': 'INTEGER',
                                                   'value': 32},
                               'maxnoofSITypes': {'type': 'INTEGER',
                                                  'value': 32},
                               'maxnoofSRBs': {'type': 'INTEGER', 'value': 8},
                               'maxnoofSliceItems': {'type': 'INTEGER',
                                                     'value': 1024},
                               'maxnoofTNLAssociations': {'type': 'INTEGER',
                                                          'value': 32},
                               'maxnoofULUPTNLInformation': {'type': 'INTEGER',
                                                             'value': 2}}}}